Provenance-Emu/Provenance

Provenance/Controller/PVControllerViewController.m

Changes the leftThumbstick to rightThumbstick

---

PVGB/GB/PVGBEmulatorCore.mm
PVGBA/GBA/PVGBAEmulatorCore.mm
PVGenesis/PVGenesis/Genesis/PVGenesisEmulatorCore.m
PVNES/NES/PVNESEmulatorCore.mm
PVSNES/PVSNES/SNES/PVSNESEmulatorCore.h
PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm
Provenance/Emulator/PVGLViewController.m

Synchronise OpenGL rendering and emulator frame rendering.

Fix SNES rendering issues

---

Provenance/Game Library/PVGameLibraryViewController.m

… on every iteration.
Greatly reduces startup time for large libraries.

Reduce startup time for large libraries. 

---

PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm

Fix MFI controller lag on SNES games

Fix MFI controller lag on SNES games

---

Provenance/Game Library/PVGameLibraryViewController.m
Provenance/Settings/PVSettingsModel.h
Provenance/Settings/PVSettingsModel.m
Provenance/Settings/PVSettingsViewController.h
Provenance/Settings/PVSettingsViewController.m
Provenance/User Interface/Provenance.storyboard
ProvenanceTV/Base.lproj/Main.storyboard
ProvenanceTV/PVTVSettingsViewController.m

Recently played games section on library.
See #317

Recent games

---

Provenance/Game Library/PVGameLibraryViewController.m

Present an alert controller with a text field
Return an array of index paths when searching for a game on the data source
(supports game being on multiple sections, e.g. 'recently played')
Will resolve the part of renaming on #173, still need a way to pick images.

Rename games on tvOS

---

Provenance/Controller/PVControllerViewController.h
Provenance/Controller/PVControllerViewController.m
Provenance/Settings/PVAppearanceViewController.m

Needed to add/tweak some preprocessor conditionals.

Fix tvOS build

---

Provenance/Emulator/PVEmulatorViewController.m
Provenance/Provenance-Info.plist

New pull request with a clean commit history.

Screenshot feature

---

Provenance/Game Library/PVGameLibrarySectionHeaderView.m
ProvenanceTV/Info.plist

Support for Dark Mode on tvOS

---

PVSupport/PVSupport/OETimingUtils.m
PVSupport/PVSupport/PVEmulatorCore.m

Fixes iPhone 7 / 7 Plus random crashes

---

.gitignore
Provenance.xcodeproj/project.pbxproj
Provenance/Provenance-Info.plist
Provenance/Settings/PVSettingsViewController.h
Provenance/Settings/PVSettingsViewController.m
Provenance/User Interface/Provenance.storyboard
ProvenanceTV/Base.lproj/Main.storyboard
ProvenanceTV/Info.plist
ProvenanceTV/PVTVSettingsViewController.m

Adds new Build Phases to create local.plist (which is ignored by git)
containing the SHA of the current branch's most recent commit and the SHA
of the commit in master from which the local branch was created. The latter
updates after rebasing against an updated master branch.
Both of these SHAs can then be seen on the Settings menu, which may be
helpful for both developers and users (who may be having issues building and
installing Provenance.

Show current and master SHA hashes in Settings

---

Provenance/Game Library/PVGame.h
Provenance/Game Library/PVGame.m
Provenance/Game Library/PVGameLibraryViewController.m

Hi.
I'm not sure you even want this feature, but I thought I'd make a pull request just in case. I added a "Toggle Favorite" option to the action sheet, making it possible to set a list of favorite games, which will be shown in their own section, on top of Recent Games. I have thousands of games in the app, and this feature helps me out a lot.

Favorite Games

---

Provenance/Game Library/PVGameLibraryViewController.m

Fixes wrong game being chosen when long-pressing search results

---

Provenance/Controller/PVControllerManager.h
Provenance/Controller/PVControllerManager.m
Provenance/Controller/PVControllerSelectionViewController.m
Provenance/Controller/iCade/PViCadeController.h
Provenance/Controller/iCade/PViCadeController.m
Provenance/Controller/iCade/PViCadeControllerViewController.m
Provenance/Controller/iCade/PViCadeReader.h
Provenance/Controller/iCade/PViCadeReader.m
Provenance/Controller/iCade/iCadeReaderView.m
Provenance/Emulator/PVEmulatorViewController.m
ProvenanceTV/Base.lproj/Main.storyboard
ProvenanceTV/PVTVSettingsViewController.m

This Pull Request brings in the commits added by @DanielFontes on his fork to address iCade and 8Bitdo controller support in issue #269.
I rebased those changes on top of the latest Provenance master and resolved the rebase conflicts.
https://github.com/jasarien/Provenance/issues/269
https://github.com/DanielFontes/Provenance
Submitting this PR so as to bring those changes into the main Provenance repo.
NOTE: I have not personally evaluated or tested these changes. Opening this PR for visibility, as I was surprised and happy to see that 8Bitdo support was added! I can and will test once my 8Bitdo controller arrives in the mail.

iCade fixes and 8Bitdo controller support

---

PVStella/PVStella/Stella/PVStellaGameCore.mm

Fixes #471 
Pad buffers were too short. Improved the mapping to include 3 fire buttons (special controllers) and color/b&W switch on extended pad.

Fix Stella MFI button mappings

---

README.mdown

Added space char : #char becomes # char

proper markdown subtitles

---

PVProSystem/ProSystemGameCore.mm

Also some minor code style cleanups.
MFi Mapping is as follows.
**Extended** Gamepad : 7800 control
- DPAD + Left joy : Joystick
- A : Fire 1
- B or X : Fire 2
- Y : Pause
- Left Shoulder : Console Reset
- Right Shoulder : Console Select
- Left Trigger : Console left difficulty
- Right Trigger : Console right difficulty
**Standard** Gamepad : 7800 control
- DPAD + Left joy : Joystick
- A : Fire 1
- B : Fire 2
- X : Console left difficulty
- Y : Console right difficulty
- Left Shoulder : Console Reset
- Right Shoulder : Console Select
I couldn't decide if difficulty switches or pause was more important with the lack of buttons on Standard gamepad. Currently there is no feedback for the position of the switches.
Here is a guide for which ROMs take use of the switches and  how. …

Fixes #547 Improve MFi mappings for 7800

---

Provenance/Emulator/PVEmulatorViewController.m

Copy over the menu button hack from https://github.com/jasarien/Provenance/pull/566/commits/47b2ecf18dcff8889dd8df9bc9928802f5f771fb?diff=unified
(Couldn't find an easy way to cherrypick/merge a single commit from a PR through Github, and I was away from my computer)

Copy over the controller menu button hack

---

README.mdown

Update Mifi controller link in readme

---

Provenance/Emulator/PVEmulatorViewController.swift
Provenance/Game Library/Models/PVSaveState.swift
Provenance/Game Library/UI/PVSaveStatesViewController.swift

Show an alert controller when selecting a save state

Support overwriting existing save states

---

Mednafen/MednafenGameCore.mm

This change will add dpad emulation to the left analog stick for PS1 similar the other cores. For PSX we only do this when the analog mode is disabled.
Give me a couple of days to test this.
I might also want to consider adding an option to disable the key combos. Games like Wing Command 3 use a lot of their own combos and these blocked. 
https://www.wcnews.com/controls.shtml#wc3ps

Adding dpad emulation to left stick when psx not in analog mode

---

Provenance/Emulator/PVEmulatorViewController.swift

Reduces it from 100 to 40. Makes it much less intrusive then before.

Reduce tvOS FPS Font size significantly

---

.gitmodules
Cores/TGBDual/.gitignore
Cores/TGBDual/PVTGBDual.xcodeproj/project.pbxproj
Cores/TGBDual/PVTGBDual/Core.plist
Cores/TGBDual/PVTGBDual/Info.plist
Cores/TGBDual/PVTGBDual/PVTGBDual.h
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore+Audio.h
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore+Audio.mm
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore+Controls.h
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore+Controls.mm
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore+Saves.h
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore+Saves.mm
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore+Video.h
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore+Video.mm
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore.h
Cores/TGBDual/PVTGBDualCore/PVTGBDualCore.mm
Provenance.xcodeproj/project.pbxproj
Provenance.xcworkspace/contents.xcworkspacedata

All builds fail due to problems while cloning into '/Users/travis/build/Provenance-Emu/Provenance/Carthage/Checkouts/SWCompression/Tests/Test Files'

added tgbdual core

---

Provenance/Settings/PVSettingsViewController.swift

Set opacity minimum to 0.5

---

PVLibrary/PVLibrary/Configuration/PVEmulatorConfiguration+Frameworks.swift
PVLibrary/PVLibrary/Importer/iCloudSync.swift
PVLibrary/PVLibrary/RealmPlatform/RomDatabase.swift
PVLibrary/PVLibrary/RealmPlatform/Utility/Extensions/Realm+Ext.swift
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/PVAppDelegate.swift
Provenance/Settings/PVSettingsViewController.swift
Provenance/Settings/WebServerActivatorController.swift

Solves compilation failures with Xcode 11.4

Updates for Xcode 11.4 / Swift 5.2, and Realm

---

Provenance/Controller/PVControllerManager.swift
Provenance/Emulator/PVEmulatorViewController.swift
Provenance/PVAppDelegate.swift

Feature/steamcontroller v1.2

---

Provenance/Settings/PVSettingsViewController.swift

This pull request updates the wiki link.

Update wiki link

---

Provenance/Settings/PVSettingsViewController.swift

This pull request makes some minor grammar changes to settings labels.

Fix settings label grammar

---

.github/ISSUE_TEMPLATE/bug-report.md

This pull request updates the supported iOS versions.
-----
[View rendered .github/ISSUE_TEMPLATE/bug-report.md](https://github.com/dnicolson/Provenance/blob/patch-1/.github/ISSUE_TEMPLATE/bug-report.md)

Update relevant iOS versions

---

Provenance.xcodeproj/project.pbxproj
Provenance/PVAppDelegate.swift
ProvenanceTV/PVTVTabBarController.swift

Just shuffling around code, this was #ifdef-ed in the AppDelegate, but seems like it should belong to it's own file in the target where it's actually used.
No behaviour changes, should just build

Move PVTVTabBarController to its own file, in the correct target

---

Cores/Yabause/PVYabause.xcodeproj/project.pbxproj
Cores/Yabause/PVYabause.xcodeproj/xcshareddata/xcschemes/gen68k.xcscheme
PVLibrary/PVLibrary.xcodeproj/project.pbxproj
PVLibrary/PVLibraryTests/PVLibraryTests.swift
Provenance.xctestplan
Provenance.xcworkspace/contents.xcworkspacedata
Provenance.xcworkspace/xcshareddata/xcschemes/Provenance.xcscheme
azure-pipelines.yml

Fixing so that CI is run on Azure correctly.
I've also been looking into Travis, but there we have a problem with `carthage bootstrap` timing out, and I didn't look into using the `rome` caching thingy.
I'm not sure what the reason for having Azure + Travis + Bitrise is though?

Fix Azure CI

---

Cores/Mednafen/PVMednafen.xcodeproj/project.pbxproj
Cores/Mednafen/mednafen/src/snes_faust/cart.cpp
Cores/Mednafen/mednafen/src/types.h

This should make it possible to build to device again.

Fix some minor issues when building PVMednafen for devices

---

.github/PULL_REQUEST_TEMPLATE.md

This pull request amends the pull request template, adjusting the screenshot heading.
-----
[View rendered .github/PULL_REQUEST_TEMPLATE.md](https://github.com/dnicolson/Provenance/blob/patch-1/.github/PULL_REQUEST_TEMPLATE.md)

Adjust screenshot heading

---

Cores/Yabause/PVYabause.xcodeproj/project.pbxproj
Provenance.xcodeproj/project.pbxproj
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/GameLaunchingViewController.swift
Provenance/Game Library/UI/PVGameMoreInfoViewController.swift
Provenance/Provenance-Info.plist
Provenance/Settings/PVSettingsViewController.swift
Provenance/Settings/SystemSettings/SystemsSettingsTableViewController.swift
Provenance/Settings/WebServerActivatorController.swift
ProvenanceTV/Info.plist
Spotlight/Info.plist
carthage.sh

This pull request fixes some grammar, orphaned file references and other fixes.
Look at each commit individually.
Run Carthage with [this fix](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) with Xcode 12.

Project file and other minor fixes

---

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift
Provenance/Settings/Cells/PVSliderCell.swift
Provenance/Settings/Cells/PVSwitchCell.swift
Provenance/Settings/SystemSettings/SystemSettingsCell.swift
Provenance/Settings/SystemSettings/SystemSettingsHeaderCell.swift

This pull request removes unnecessary tvOS 10.0 conditionals as tvOS 10 is a minimum requirement.

Remove tvOS 10 conditionals

---

Provenance.xcodeproj/project.pbxproj
Provenance/Emulator/PVEmulatorViewController.swift
Provenance/Emulator/PVEmulatorViewController~iOS.swift
Provenance/Emulator/PVEmulatorViewController~tvOS.swift

Reverts Provenance-Emu/Provenance#1489

Revert "Fix memory leak in pause menu"

---

PVSupport/PVSupport.xcodeproj/project.pbxproj

This pull request removes `(null)` references.

Remove (null) references

---

Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/HISTORY.txt
Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/genplusgx_source/sound/ym2413.c
Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/genplusgx_source/sound/ym2612.c
Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/genplusgx_source/sound/ym3438.c
Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/genplusgx_source/sound/ym3438.h
Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/libretro/libretro.c

Syncs up the various YM3438 and YM2612 audio fixes from GenesisPlusGX Mainline for Pv.

Sync up to GenesisPlusGX Mainline 1e0d2dad8f967ed9dae95841ad0b707a6d881aa4

---

.gitmodules

Moves Reicast submodule from JoeMatt to Provenance-EMU

Move Reicast to Prov org

---

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/GameLaunchingViewController.swift
Provenance/Game Library/UI/PVConflictViewController.swift
Provenance/Settings/PVCoresTableViewContorller.swift
Provenance/Settings/PVSettingsViewController.swift
Provenance/User Interface/Default.xib
Provenance/Utilities/PVGameLibraryUpdatesController.swift
Provenance/Utilities/PVLogViewController.m

This pull request replaces existing "..." characters with an ellipsis ("…") character for consistency, ellipses are already widely used in the project.
Additionally, ellipses were removed from some buttons and added to the loading header on iOS.

Add ellipsis to "Loading" title

---

ProvenanceTV-Bridging-Header.h

fix tv include compile error

---

Cores/Mednafen/MednafenGameCore.mm

Fix virtual boy crash

---

Cores/Mednafen/MednafenGameCore.mm
PVLibrary/PVLibrary/Importer/Services/GameImporter.swift
PVLibrary/PVLibrary/PVGameLibrary+Migration.swift
PVLibrary/PVLibrary/RealmPlatform/Entities/Files/PVFile.swift
PVLibrary/PVLibrary/RealmPlatform/Entities/PVGame.swift
PVSupport/EmulatorCore/PVEmulatorCore.h
PVSupport/EmulatorCore/PVEmulatorCore.m
PVSupport/PVSupport/Audio/OEGameAudio.m
PVSupport/PVSupport/RealTimeThread.m
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
Provenance/Game Library/UI/PVGameMoreInfoViewController.swift
Provenance/Settings/PVSettingsViewController.swift
azure-pipelines.yml

Redo of #1569 without completely removing iCloud
- Fix some cast warnings
- gameimporter fix an unnecesary exception throw
- pblibrary re-fix the exception thing
- Fix warning in gameaudio.m
- mednafen: fix broken nes and other control inputs
- pvgamelib async call update migration
- PVFile.swift better handle missing files
- Fix iCloud or whatever is causing private in paths

Fix missing roms on rescan

---

Provenance/Emulator/PVEmulatorViewController.swift
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/PVGameMoreInfoViewController.swift
Provenance/User Interface/Themes/UIView+Theming.swift

This pull request removes conditionals for iOS 11, the deployment target was recently (https://github.com/Provenance-Emu/Provenance/pull/1533/commits/510e3262fadd5ff085fedd3cb43834ac8ffd523e) updated to support iOS 11 and above.

Remove iOS 11 conditionals

---

.gitmodules
Cores/Desmume2015/BuildFlags.xcconfig
Cores/Desmume2015/PVDesmume2015.xcodeproj/project.pbxproj
Cores/Desmume2015/PVDesmume2015.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Cores/Desmume2015/PVDesmume2015.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Cores/Desmume2015/PVDesmume2015.xcodeproj/xcshareddata/xcschemes/PVDesmume2015-iOS 1.xcscheme
Cores/Desmume2015/PVDesmume2015.xcodeproj/xcshareddata/xcschemes/PVDesmume2015-iOS.xcscheme
Cores/Desmume2015/PVDesmume2015.xcodeproj/xcshareddata/xcschemes/PVDesmume2015-tvOS.xcscheme
Cores/Desmume2015/PVDesmume2015.xcodeproj/xcshareddata/xcschemes/PVPVDesmume2015-tvOS.xcscheme
Cores/Desmume2015/PVDesmume2015/Core.plist
Cores/Desmume2015/PVDesmume2015/Info.plist
Cores/Desmume2015/PVDesmume2015/PVDesmume2015.h
Cores/Desmume2015/PVDesmume2015/emu.cfg
Cores/Desmume2015/PVDesmume2015Core/Audio/PVDesmume2015+Audio.h
Cores/Desmume2015/PVDesmume2015Core/Audio/PVDesmume2015+Audio.mm
Cores/Desmume2015/PVDesmume2015Core/Audio/PVDesmume2015+AudioTypes.h
Cores/Desmume2015/PVDesmume2015Core/Audio/PVDesmume2015+CoreAudio.h
Cores/Desmume2015/PVDesmume2015Core/Audio/PVDesmume2015+CoreAudio.mm
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core+Audio.h
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core+Audio.m
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core+Controls.h
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core+Controls.mm
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core+Saves.h
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core+Saves.m
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core+Video.h
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core+Video.m
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core.h
Cores/Desmume2015/PVDesmume2015Core/Core/PVDesmume2015Core.mm
Cores/Desmume2015/PVDesmume2015Core/PVDesmume2015.mm
Provenance.xcworkspace/contents.xcworkspacedata

Signed-off-by: Joseph Mattello <mail@joemattiello.com>

Add Desmume2015 core

---

Provenance/User Interface/zh-Hans.lproj/Provenance.strings

translate word

---

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift

Add a few tweaks to tvOS UX
* make the navbar translucent, using same alpha color as section headers
* make sure a collection view cell does not go above a section header.
* make the section font a tad bigger.

tvOS UX tweaks

---

ProvenanceTV/Story Boards/en.lproj/Provenance.storyboard

Unify the Blue'ish tintColor used for the various GameLibraryView Pv Buttons on tvOS

tintColor fix for Pv Buttons on tvOS

---

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift

Adds subtle blurEffect to navBar on tvOS.

Adds subtle blurEffect to navBar on tvOS

---

Provenance/Emulator/PVEmulatorVC/PVEmulatorViewController.swift

Clarify Game Speed %'s, Slow is 20% , Normal is 100% and fast is 500%

Clarify Game Speed %'s

---

Provenance/Controller/PVControllerManager.swift
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/QuickTableViewController/QuickTableViewController.swift
ProvenanceTV/TVAlertController.swift

more Game Controller Nav, work in progress....

Game Controller UX for UITableView and UINavigationController, and a start of GameLibrary UX

---

Provenance/Emulator/Shaders/crt_filter_ps.metal

- Adds in a new MTL specific mod function to match the one used in our GLSL CRT Shader. This gets us the visual match to the GLSL reference CRT Shader.
- Adds in a clamp function to the edgeMask function to get rid of any excessive white-out streaking due to the edge pixels going crazy negative.
- Simplify uv processing if no Warping is selected.

MTL CRT Shader fixes

---

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift

handle game controller UX navigation the in library view
A = select (and run) game/item
Y = get context menu on game/item
X = open settings

game controller UX, made Y be long-press, and some clean up

---

Provenance/Resources/ru.lproj/Strings.strings

- add Russian localization to the app
Notes: haven't used Russian UI in 10+ years, some translations might be off.

add russian translations

---

Build-iOS.xcconfig
Build-tvOS.xcconfig
Build-watchOS.xcconfig
Build.xcconfig
CHANGELOG.md
Cores/Genesis-Plus-GX/PVGenesis.xcodeproj/project.pbxproj
Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/GenesisOptions.swift
Cores/Genesis-Plus-GX/PVGenesis/Genesis/PVGenesisEmulatorCore.m
Cores/Mednafen/MednafenGameCore.swift
Cores/Mupen64Plus/MupenOptions.swift
PVLibrary/PVLibrary/Configuration/PVEmulatorConfiguration.swift
PVLibrary/PVLibrary/Database/PVGameLibrary.swift
PVLibrary/PVLibrary/Resources/systems.plist
PVSupport/Sources/PVSupport/CoreOptions/CoreOptions+Serialization.swift
PVSupport/Sources/PVSupport/CoreOptions/CoreOptions.swift
Provenance.xcodeproj/project.pbxproj
Provenance/Controller/PVControllerManager.swift
Provenance/Emulator/CoreOptionsViewController.swift
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift
Provenance/Settings/PVSettingsViewController.swift

null
-----
[View rendered CHANGELOG.md](https://github.com/Provenance-Emu/Provenance/blob/feature/segaoptoins/CHANGELOG.md)

Sega Options

---

ProvenanceTV/TVAlertController.swift

To be revisited at a later date for tvOS.

Make Menu icons iOS only

---

Provenance/http/GCDWebUploader/GCDWebUploader.bundle/Contents/Resources/en.lproj/Localizable.strings

Broken WIki page link fixed. Wiki link now opens in new tab to keep the browser on the web UI.

Fix broken wiki link, minor UX improvements

---

Cores/Mupen64Plus/MupenGameCore.m
PVSupport/Sources/PVSupport/CoreOptions/CoreOptions+Protocols.swift
PVSupport/Sources/PVSupport/CoreOptions/CoreOptions.swift
PVSupport/Sources/PVSupport/CoreOptions/Types/CoreOptionMultiValue.swift
Provenance/Emulator/CoreOptionsViewController.swift

- NOTICKET Options tableview popover rect fixed
- NOTICKET core options enum default fixed

#1888 N64 16x9

---

.gitmodules
Cores/DosBox/BuildFlags.xcconfig
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore+Audio.h
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore+Audio.m
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore+Controls.h
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore+Controls.mm
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore+Saves.h
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore+Saves.m
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore+Video.h
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore+Video.m
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore.h
Cores/DosBox/PBDosBoxCore/Core/PVDosBoxCore.mm
Cores/DosBox/PBDosBoxCore/DosBoxGameCore.h
Cores/DosBox/PBDosBoxCore/DosBoxGameCore.mm
Cores/DosBox/PBDosBoxCore/PVDosBox.mm
Cores/DosBox/PVDosBox.xcodeproj/project.pbxproj
Cores/DosBox/PVDosBox.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Cores/DosBox/PVDosBox.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Cores/DosBox/PVDosBox.xcodeproj/xcshareddata/xcschemes/PVDosBox-iOS.xcscheme
Cores/DosBox/PVDosBox.xcodeproj/xcshareddata/xcschemes/PVDosBox-tvOS.xcscheme
Cores/DosBox/PVDosBox.xcodeproj/xcshareddata/xcschemes/PVPlay-iOS.xcscheme
Cores/DosBox/PVDosBox.xcodeproj/xcshareddata/xcschemes/PVPlay-tvOS.xcscheme
Cores/DosBox/PVDosBox.xcodeproj/xcshareddata/xcschemes/dos-box-iOS.xcscheme
Cores/DosBox/PVDosBox.xcodeproj/xcshareddata/xcschemes/play-iOS.xcscheme
Cores/DosBox/PVDosBox.xcodeproj/xcshareddata/xcschemes/play-tvOS.xcscheme
Cores/DosBox/PVDosBox/Core.plist
Cores/DosBox/PVDosBox/Info.plist
Cores/DosBox/PVDosBox/PVDosBox.h
Provenance.xcworkspace/contents.xcworkspacedata

- Add dosbox-pure
- add a working project for dosbox

[WIP][Core] DosBox Pure

---

Build.xcconfig
Cores/Atari800/Atari800Core/Source/ATR800GameCore.m
Cores/Mupen64Plus/MupenGameCore+Controls.m
PVLibrary/PVLibrary/Resources/systems.plist
PVSupport/Sources/PVSupport/EmulatorCore/Features/Controls.swift
Provenance/Controller/PVControllerViewController.swift
Provenance/Controller/Systems/PVAtari5200ControllerViewController.swift
Provenance/Controller/Systems/PVDreamcastControllerViewController.swift
Provenance/Controller/Systems/PVN64ControllerViewController.swift
Provenance/Controller/Systems/PVVectrexControllerViewController.swift

Signed-off-by: Joseph Mattello <mail@joemattiello.com>

fixes #1915 joystick layout busted

---

Cores/Mednafen/MednafenGameCore.mm

Signed-off-by: Joseph Mattello <mail@joemattiello.com>

refs #1765 fix non-dualshock start in  Saturn

---

PVLibrary/PVLibrary/Importer/Services/GameImporter.swift
PVSupport/Sources/PVSupport/Settings/PVSettingsModel.swift
Provenance.xcodeproj/project.pbxproj
Provenance/Controller/JSButton.swift
Provenance/Controller/JSDPad.swift
Provenance/Controller/Moveable.swift
Provenance/Controller/PVButtonGroupOverlayView.swift
Provenance/Controller/PVControllerViewController.swift
Provenance/Provenance-Bridging-Header.h
Provenance/Services/ApplicationMonitor.swift
Provenance/Services/LocationManager.swift
Provenance/Settings/PVSettingsViewController.swift

Allows drag/moving controller buttons.

[Feature] Draggable Controller buttons

---

Cores/Mednafen/MednafenGameCore.mm
Cores/Mupen64Plus/MupenGameCore.m
Cores/snes9x/PVSNES/SNES/PVSNESEmulatorCore.mm

Signed-off-by: Joseph Mattello <mail@joemattiello.com>

SNES9X external controller fix

---

Provenance/Controller/PVControllerSelectionViewController.swift

This pull request simplifies and fixes how the table cells update after changing the controller, at the moment the focus changes are unpredictable.
Test changing controller assignments.

Fix controller selection table cell focus

---

Provenance/NewUI/Components/ViewControllerResolver.swift

This pull request fixes a crash on iOS 16, the fix is outlined [here](https://developer.apple.com/forums/thread/709433).

Fix SwiftUI crash on iOS 16

---

Provenance/Settings/Cells/PVSliderCell.swift
Provenance/Settings/Cells/SliderCell.swift
Provenance/User Interface/Themes/UIColor+Theming.swift

This pull request fixes the cell text alignment for UISlider elements on newer devices. The devices "iPhone 14 Pro" and "iPhone SE (3rd generation)" were tested in the Simulator.

Fix slider cell text alignment and other style fixes

---

PVSupport/Sources/PVSupport/Logging/PVCocoaLumberJackLogging.swift
PVSupport/Sources/PVSupport/Logging/PVLogging.h

This pull request fixes a crash when the "Select File" log button is used.

Fix logs crash

---

Provenance/Settings/WebServerActivatorController.swift

This pull request uses the same web server alert text the same on tvOS and iOS.

Make web server alerts consistent

---

PVSupport/PVSupport.xcodeproj/project.pbxproj
Provenance.xcodeproj/project.pbxproj

This pull request replaces some remaining "com.provenance-emu…" bundle identifiers, it's not clear if this will break anything though.

Replace remaining com.provenance-emu with org

---

Provenance/Utilities/PVLogViewController.m
Provenance/Utilities/PVLogViewController.xib

This pull request replaces the black background live log and white background file logs with the system background color.

Use system colors for logs

---

PVSupport/Sources/PVSupport/Controller/HapticsManager.swift
PVSupport/Sources/PVSupport/Performance/PerformanceView.swift
Provenance/Controller/GCControllerExtensions.swift
Provenance/Controller/PVControllerManager.swift
Provenance/Emulator/MTLViewController.swift
Provenance/Emulator/PVEmulatorVC/PVEmulatorViewController+Controllers.swift
Provenance/Emulator/PVEmulatorVC/PVEmulatorViewController+CoreOptions.swift
Provenance/Emulator/PVEmulatorVC/PVEmulatorViewController.swift
Provenance/Emulator/PVGLViewController/PVMetalViewController.m
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/QuickTableViewController/Model/Icon.swift
Provenance/Game Library/UI/QuickTableViewController/QuickTableViewController.swift
Provenance/PVAppDelegate.swift
Provenance/Services/ApplicationMonitor.swift
Provenance/Services/LocationManager.swift
Provenance/Services/PublishedPipeline.swift
Provenance/User Interface/SwiftUI/GameLibraryView.swift
Provenance/User Interface/Themes/Theme.swift
ProvenanceTV/TVAlertController.swift

General cleanup (rebase)

---

Cores/GameMusicEmu/PVGME.xcodeproj/project.pbxproj
Cores/Gearcoleco/PVGearcoleco.xcodeproj/project.pbxproj
Cores/PicoDrive/PVPicoDrive.xcodeproj/project.pbxproj
Cores/PokeMini/PVPokeMini.xcodeproj/project.pbxproj
Cores/Potator/PVPotator.xcodeproj/project.pbxproj
Cores/ProSystem/PVProSystem.xcodeproj/project.pbxproj
Cores/Stella/PVStella.xcodeproj/project.pbxproj
Cores/TGBDual/PVTGBDual.xcodeproj/project.pbxproj
Cores/ep128emu/PVEP128Emu.xcodeproj/project.pbxproj
Cores/opera/PVOpera.xcodeproj/project.pbxproj
PVLibrary/PVLibrary/Importer/iCloudSync.swift
PVSupport/Sources/PVSupport/Settings/PVSettingsModel.swift
Provenance.xcodeproj/project.pbxproj
Provenance/Controller/JSDPad.swift
Provenance/Controller/PVControllerManager.swift
Provenance/Controller/PVControllerViewController.swift
Provenance/Controller/Systems/PVN64ControllerViewController.swift
Provenance/Emulator/PVGLViewController/PVGLViewController.m
Provenance/Emulator/PVGLViewController/PVMetalViewController.m
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
Provenance/Provenance-Bridging-Header.h
Provenance/Settings/PVSettingsViewController.swift
Provenance/http/PVWebServer.m

refs #2026
Adds option for joystick on/off when keyboard connected
Still has some issues,
1. BG color isn't clear after drag
2. Disapears after drag

Joystick fixes - draggable and clear BG, option for on/off with keyboard

---

Provenance/Controller/PVControllerSelectionViewController.swift
Provenance/Controller/PViCadeControllerViewController.swift
Provenance/Game Library/UI/CollectionViewInACell/CollectionViewInCollectionViewCell.swift
Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift
Provenance/Game Library/UI/GameLaunchingViewController.swift
Provenance/Game Library/UI/PVConflictViewController.swift
Provenance/Game Library/UI/PVGameMoreInfoViewController.swift
Provenance/NewUI/PVRootViewController+DelegateMethods.swift
Provenance/PVAppDelegate.swift
Provenance/Settings/PVAppearanceViewController.swift
Provenance/Settings/PVSettingsViewController.swift
Provenance/Settings/SystemSettings/SystemsSettingsTableViewController.swift
Provenance/User Interface/Themes/Theme.swift
Provenance/User Interface/en.lproj/Provenance.storyboard
Provenance/User Interface/es.lproj/Provenance.storyboard
Provenance/User Interface/it.lproj/Provenance.storyboard
Provenance/User Interface/ja.lproj/Provenance.storyboard
Provenance/User Interface/nl.lproj/Provenance.storyboard
Provenance/User Interface/ru.lproj/Provenance.storyboard

This pull request removes some redundant styles and some minor fixes.

Remove unneeded styling and minor fixes

---

.github/workflows/build.yml
.gitignore
Cores/Mednafen/PVMednafen.xcodeproj/project.pbxproj
PVLibrary/PVLibrary/Domain/Protocols/SystemProtocol.swift
PVLibrary/PVLibrary/Domain/System.swift
PVLibrary/PVLibrary/RealmPlatform/Entities/PVSystem.swift
PVLibrary/PVLibrary/Resources/systems.plist
Provenance.xcodeproj/xcshareddata/xcschemes/Spotlight.xcscheme
Provenance.xcworkspace/xcshareddata/xcschemes/Provenance-Release.xcscheme
Provenance/Game Library/UI/PVConflictViewController.swift
Provenance/http/GCDWebServer/Core/GCDWebServer.m
azure-pipelines.yml

action to build and upload on PRs

GitHub build action

---

Provenance/User Interface/Themes/Theme.swift

This pull request fixes the status bar color. Using `UIApplication.shared.keyWindow` is deprecated in iOS 13 and `DispatchQueue.main.async` is needed for the status bar to update.

Fix status bar color

---

Provenance/Controller/PVControllerSelectionViewController.swift

This pull request improves the handling of controller changes, the removal of one line in https://github.com/Provenance-Emu/Provenance/pull/1968/files#diff-176af279eafa097e9d9add553ac1866b09112e71b37f0b51423ee2a8e1405b24L91 has been reintroduced which also makes https://github.com/Provenance-Emu/Provenance/pull/1999/files less relevant.

Improve controller select state fix

---

Cores/Play/PVPlayCore/Core/CGSH_MTLViewController.swift
Cores/Play/PVPlayCore/Core/PVPlayCore+Saves.mm
Cores/Play/PVPlayCore/Core/PVPlayCore+Video.mm
Cores/Play/PVPlayCore/Core/PVPlayCore.h
Cores/Play/PVPlayCore/Core/PVPlayCore.mm
Cores/Play/PVPlayCore/Core/PVPlayCore.swift

This implements resolution upscaling and screen resizing for the Vulkan renderer. This completes the initial features implementation related to playing playstation 2 games on Play! and now I'm going to play the games =] As always this is an amazing project, bringing endless hours of fun.
* Inside Cores/Play/cmake -> "rm -fr CMake*" -> "sh update.sh"
* Metal Renderer is updated to auto adjust size based on iPhone / iPad ..etc.
* In Provenance Settings, choose Vulkan and/or OpenGL under Play core, Choose any resolution factor, the game should play
* I'll create separate PR for cmake / MoltenVK
https://github.com/Provenance-Emu/Provenance/pull/2072

Play: Resolution Upscaling and Screen Size Adjustments on vulkan

---

CoresRetro/RetroArch/PVRetroArch/Core.plist

This makes it consistent with the other Snes9x core.

Fix Snes9x stylization

---

Provenance/Settings/PVSettingsViewController.swift

Replace Cores icon and add trailing period

---

.github/workflows/build.yml
Provenance/PVAppDelegate.swift

tvOS: Fix to compile on tvOS

---

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift
Provenance/User Interface/Themes/Theme.swift

Fixes the game header styles when the theme is changed.

Fix game header styles

---

Provenance/PVAppDelegate.swift

Fixes an issue introduced in #2235.

Fix initial interface style

---

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift

Fix long press on tvOS

---

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift

Use eye symbol for hide item

---

Provenance/Emulator/PVEmulatorVC/PVEmulatorViewController.swift

Sets the theme again on quit to ensure the status bar color is updated.

Fix status bar after game quit

---

Provenance/Game Library/UI/GameLaunchingViewController.swift

https://github.com/Provenance-Emu/Provenance/assets/2276355/6655c90c-3e76-4e3e-bf06-6619ee3eb3db

Prevent library from shuffling when starting a game

---

CoresRetro/RetroArch/PVRetroArchCore/Core/PVRetroArchCore+Controls.swift

Hide controller when RetroArch keyboard is active

---

.gitmodules
Provenance.xcodeproj/project.pbxproj
Provenance.xcworkspace/contents.xcworkspacedata
Provenance.xcworkspace/xcshareddata/swiftpm/Package.resolved

emuThree repos are down. There’s a replacement, but it will take work to get it to work. I removed all references from the project but kept the project file for future porting reference.
Also had to remove Citra references. We weren't using it yet anyway.

Fix broken CI by removing emuThree

---

PVLibrary/Sources/PVLibrary/Importer/Models/GameImporterError.swift
PVLibrary/Sources/PVLibrary/Importer/Models/ImportQueueItem.swift
PVLibrary/Sources/PVLibrary/Importer/Services/GameImporter/GameImporter.swift
PVUI/Sources/PVSwiftUI/Imports/ImportTaskRowView.swift

adds error description if a game import fails to help identify what went wrong.

Add Game Importer Error Status to Import View

---

PVUI/Sources/PVSwiftUI/Imports/SystemSelectionView.swift

sorts system conflicts by name for easier reading.

BugFix - Sort Conflicting systems by name in SystemSelectionView
