Provenance/Game Library/PVGameImporter.m
This change only searches text leading up to extraneous characters such as ( or [, etc. For me, this helps grab images/titles for certain roms that did not match the MD5 hash, for example because they are patched with a custom translation.
=> Rom filename lookup fails if extraneous characters are in rom filename.

PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm, Provenance/Controller/PVNESControllerViewController.m
I haven't spent enough time to validate that these are correct in all cases, but in my testing on tvOS using a bluetooth controller, they work correctly and fix a couple issues.
One changes the way NES controller dpad events are processed, as zelda and other games were quite difficult to control, especially with the joystick.
The other change adds 1 to the player # for the SNES controller, as it appears to be 1 based. Without the change, the controller simply doesn't seem to work. 
It's entirely possible that these break the iOS onscreen controller, but at the very least they might be a starting point for fixing the issues I've noticed.
=> Some tvOS controller fixes

Provenance/Controller/PVGBAControllerViewController.m, Provenance/Controller/PVGBControllerViewController.m, Provenance/Controller/PVGenesisControllerViewController.m, Provenance/Controller/PVNESControllerViewController.m, Provenance/Controller/PVSNESControllerViewController.m
Diagonal controls (i.e. direction UP and Right at the same time) are being detected as either an horizontal or a vertical direction.
The following code is causing the issue by skipping pressed direction:
```
&& fabsf(xAxis) > fabsf(yAxis)
&& fabsf(xAxis) <= fabsf(yAxis)
```
=> Diagonal controls from dpad and analog stick are not detected

Provenance/Controller/iCade/PViCadeControllerViewController.m, Provenance/Game Library/PVConflictViewController.m, Provenance/Settings/PVSettingsViewController.m, Provenance/User Interface/Provenance.storyboard
Fixed a bug that occurred when “Refresh Game Library” or “Empty image
cache” were selected and “No” was selected for the alert, causing the
“Done” UIBarButton Item to become “unbolded”
Fixed a bug in which selecting “Controller Settings” and going back did
not clear its selection
Replaced the accessory for iCade controllers to a checkmark accessory
Removed the cell separators when there are no conflicts
=> Some Settings UI fixes

Provenance/Game Library/PVGameImporter.m
For example, games such as B.O.B. were not grabbing the correct artwork.
=> Fix grabbing ROM metadata for titles that include periods

Provenance/Emulator/PVEmulatorConfiguration.h, Provenance/Emulator/PVEmulatorConfiguration.m, Provenance/Resources/systems.plist, README.mdown
https://en.wikipedia.org/wiki/SG-1000
Genesis Plus GX has support for it, so why not expose it. I've tested this and it works.
The only thing I don't quite understand is what PVDatabaseID should be set to in systems.plist for this system.  It is currently 33, the same as Sega Genesis. Let me know what it should be and I can update it to the correct value.
=> Exposed Sega SG-1000 support

Provenance.xcodeproj/project.pbxproj, Provenance/Controller/iCade/PViCadeControllerViewController.m, Provenance/Controller/iCade/PViCadeSteelSeriesController.h, Provenance/Controller/iCade/PViCadeSteelSeriesController.m, Provenance/Controller/iCade/kICadeControllerSetting.h, Provenance/Controller/iCade/kICadeControllerSetting.m
This change adds a more appropriate controller mapping for the SteelSeries Free controller - the code is based on the iCade8Bitdo implementation. I set the buttons up to mirror the layout of the SNES pad as this most closely matches the physical layout of the controller, but tested with the Genesis emulator and it also works well.
=> Add controller mapping for SteelSeries Free

PVNES/NES/PVNESEmulatorCore.mm
Nintendo recommends resting the thumb over the west and south buttons on a 4-button SNES-type controller in place of B and A on a 2-button NES-type controller. This helps prevent [repetitive strain injury and wrist fatigue](https://en.wikipedia.org/wiki/Nintendo_thumb) by keeping the thumbs in an inward, upright position.
=> Use Nintendo’s 4-button to 2-button mappings

Provenance.xcodeproj/project.pbxproj, Provenance/Categories/RLMRealmConfiguration+GroupConfig.h, Provenance/Categories/RLMRealmConfiguration+GroupConfig.m, Provenance/Controller/PVControllerViewController.m, Provenance/Emulator/PVEmulatorConfiguration.h, Provenance/Emulator/PVEmulatorConfiguration.m, Provenance/Emulator/PVEmulatorConstants.h, Provenance/Emulator/PVEmulatorConstants.m, Provenance/Game Library/PVGameImporter.m, Provenance/Game Library/PVGameLibraryViewController.m, Provenance/PVAppDelegate.h, Provenance/PVAppDelegate.m, ProvenanceTV/PVAppConstants.h, ProvenanceTV/PVAppConstants.m, ProvenanceTV/Provenance.entitlements, TopShelf/Info.plist, TopShelf/PVRecentGame+TopShelf.h, TopShelf/PVRecentGame+TopShelf.m, TopShelf/ServiceProvider.h, TopShelf/ServiceProvider.m, TopShelf/TopShelf.entitlements
Fix: https://github.com/jasarien/Provenance/issues/145
This PR introduces the Top Shelf feature to the tvOS target by showing the recently played games, and deep-linking to them.
- Introduces the top shelf app extension
- Moves the Realm DB to a shared app group so the main app and the top shelf target can access it
- refactors a bunch of defines and duplicate logic into shared classes/categories
- add URLScheme to tvOS target
1. Enable App Groups on the TopShelf target, and specify an App Group ID
Provenance Project -> TopShelf Target -> Capabilities Section -> App Groups
2. Enable App Groups on the Provenance TV target, using the same App Group ID
3. Define the value for `PVAppGroupId` in `PVAppConstants.m` to that App Group ID
=> tvOS Top Shelf

README.mdown
Fixed the copyright dates and made a few other changes to README.mdown to make things a little more clear in an effort to hopefully prevent comments on Issues regarding new cores and other things.
=> README.mdown 2016 fix & other changes to prevent comments on issues

Provenance/Game Library/PVGameLibraryViewController.m
Fixes #290. Fix for issue where UIKeyboardWillHideNotification is unavailable when a tvOS target is built. Target checks added to keyboard notification actions and renameTextField delegate methods (not currently utilised in tvOS app).
=> Fix unavailable tvOS API build error

Provenance/Controller/PVControllerViewController.m, Provenance/Emulator/PVGLViewController.m
Makes minor adjustments to how elements are laid out on screen, making it more comfortable to play in portrait orientation.
iPad, iPhone 6+, and iPhone 4s in portrait and landscape
=> Adjustments to control layout

PVSupport/PVSupport/PVEmulatorCore.h, PVSupport/PVSupport/PVEmulatorCore.m, Provenance.xcodeproj/project.pbxproj, Provenance/Emulator/PVEmulatorViewController.m, Provenance/Emulator/PVGLViewController.m
Adds a new action sheet menu while in-game, allowing for more control over game speed. This makes things like the casino in Pokemon Yellow easier to beat. [Demo video](https://www.dropbox.com/s/5d0q7haumtx3l6o/speeds.mov?dl=0)
=> Allow game speed to be sped up or slowed down

Provenance/Emulator/PVEmulatorViewController.m
Use a tap gesture recognizer since it will override the default tvOS
'back' functionality.
Resolves #311
=> Fix menu button during gameplay on tvOS 9.2

Provenance/Controller/iCade/iCadeReaderView.m
Fix for issue where emulator stalls on hitting buttons quickly. Buffer size increased to prevent it clearing too often when buttons are pressed very quickly.
=> Increase buffer size to fix controller issue

PVGB/GB/libgambatte/src/mem/cartridge.cpp
Some Gameboy games such as Pokemon and Little Sound DJ (http://www.littlesounddj.com/) require 128k flash save files. Provenance only supports 32k currently.
Libgambatte core has already been updated to support 128k saves but a lot of emulators (not just Provenance) have not yet updated the libraries with these changes.
I have added the changes needed; tested with LSDJ and it works great.
=> Added support for Gameboy 128k save files

Provenance/Game Library/PVGameImporter.m
Fixes many cases of #246 by adding an Order by to the SQLite 'likeQuery'.  The order by sorts the results into an order that favors matches that begin with the same string as the passed in 'romFileName' key.
With the example given in #246 of 'Super Mario World', the first 3 results are now as follows:
```
{
boxImageURL = "http://img.gamefaqs.net/box/6/2/6/14626_front.jpg";
gameTitle = "Super Mario World";
region = Europe;
romFileName = "Super Mario World (Europe) (Rev 1).sfc";
systemShortName = SNES;
},
{
boxImageURL = "http://img.gamefaqs.net/box/6/2/6/14626_front.jpg";
gameTitle = "Super Mario World";
region = Europe;
romFileName = "Super Mario World (Europe).sfc";
systemShortName = SNES;
},
{
boxImageURL = "http://img.gamefaqs.net/box/6/2/5/14625_front.jpg";
gameTitle = "Super Mario …
```
=> Fix #246: Add Order By to Like Query to get a more favorable rom match

Provenance/Controller/PVControllerViewController.m
Tested and working. Fixes #262.
=> Fix #262: Hide unnecessary touch controls if system is Game Boy or GBA

PVSNES/PVSNES/SNES/PVSNESEmulatorCore.mm, PVSupport/PVSupport.xcodeproj/project.pbxproj, PVSupport/PVSupport/PVGameControllerUtilities.h, PVSupport/PVSupport/PVGameControllerUtilities.m, Provenance/Emulator/PVEmulatorViewController.m
This adds improved logic for controllers with thumbsticks to determine the current direction of either stick. Before this change, the logic alwasy preferred the yAxis of the thumbstick making it difficult to move along the xAxis in games. I started by adding the directional support to the SNES emulator since that's what I've been playing, but I put the logic into a shared class so it can be easily used in the other emulator cores. Please let me know if I put files in the right places / if I should add this axis support to the other emulator cores as well. Thanks!
=> Add better support for axis directions on extended game controllers

Provenance.xcodeproj/project.pbxproj, Provenance/Categories/UIImage+Color.h, Provenance/Categories/UIImage+Color.m, Provenance/Game Library/PVGameLibraryCollectionViewCell.h, Provenance/Game Library/PVGameLibraryCollectionViewCell.m, Provenance/Game Library/PVGameLibraryViewController.m
This changes the game library cell to use the built-in focus engine / animation. I added a category on UIImage to generate an image with a color and text so focus would apply to games without artwork as well. I also wanted to replicate the same logic that the tvOS home screen uses for the titles, so they don't display by default, and instead animate it when that item comes into focus.
This is just a proposal, the code is a little messy and I'm happy to clean it up if this is something you're interested in doing with the project. Here are screenshots of tvOS and iOS versions
=> Use default animation when focusing in the game library

Provenance/Controller/PVControllerManager.h, Provenance/Controller/PVControllerManager.m, Provenance/Controller/PVControllerSelectionViewController.m
If an extended controller is connected, assign it to an empty slot or to a slot used by a micro gamepad.
Look for available controllers once a controller is disconnected.
Refresh controller selection view controller once a controller is automatically assigned.
Fix #361
=> Always prefer a gamepad over the Siri Remote

Provenance/Emulator/PVEmulatorViewController.m
isShowingMenu was not being reset after hitting swap disk. Fixes #342
=> Fix menu button not working after FDS disk swap

Provenance/Game Library/PVGame.h, Provenance/Game Library/PVGame.m, Provenance/Game Library/PVGameLibraryCollectionViewCell.h, Provenance/Game Library/PVGameLibraryCollectionViewCell.m, Provenance/Game Library/PVGameLibraryViewController.m, Provenance/Game Library/PVMediaCache.h, Provenance/Game Library/PVMediaCache.m, ProvenanceTV/PVAppConstants.h, ProvenanceTV/PVAppConstants.m, ProvenanceTV/PVSearchViewController.m
Hi,
I worked a little on the Game Library and now the collection view scrolls very smooth. I implemented a NSOperationQueue to download images and I set the max resolution to 200x200 for mobile devices and 400x400 for Apple TV.
I'm also preparing a set of placeholder images for the cartridge without artwork. I already modified the PVGame model to support that. What do you think about that?
Bye,
Stefano
=> Game library scrolls very smooth now.

Provenance/Controller/PVControllerManager.m
When tapping Disconnect iCade, it brings the on-screen controller back. Reconnecting iCade hides it again.
=> Handle 8Bitdo disconnect and reconnect.

Provenance/Resources/systems.plist, README.mdown
A bit strange to have these both in a  single pull request, but I did not feel right with just a README correction pull request.
This has a few minor corrections/additions to the README such as Taptic Engine Feedback.
However, the main reason for this pull request is to correct the SG-1000 controls.  I was able to obtain a Test Cartridge Rom and realized that the second button was actually not working.  I also moved the buttons to be horizontally next to each other to more accurately match a real controller.
=> Corrections to README and SG-1000 Controls

README.mdown
Title explains it.
These were introduced in the README when JoeMatt's Atari & 32X emulators were merged.
=> Fix some missing punctuation in README

Provenance/Emulator/PVEmulatorViewController.m
Increases the font of FPS label for the AppleTV build. (based on request https://github.com/jasarien/Provenance/pull/459#issuecomment-270857762)
=> Increase FPS label size for TV

Provenance/Game Library/PVGameImporter.h, Provenance/Game Library/PVGameImporter.m, Provenance/Game Library/PVGameLibraryViewController.m, Provenance/http/GCDWebUploader/GCDWebUploader.bundle/index.html
Adds a directory watcher, similar to the ROMs directory watcher, that will import image file to matching game cover art.
> You can upload new cover art images by uploading a *.zip file into the Cover Art/ directory. The images need to be named the same as their ROM (IE, “kart fighter.nes.png” will update the artwork on “kart fighter.nes”. ROM Filenames can be found in the “com.provenance.*” directories). Then close the web server and Provenance will attempt to import them.
Issue #286
=> Ability to Change Cover Art via Web Server’s UI

Provenance/Controller/PVControllerViewController.m
Fixes the problem described in issue #520 - Controls appearing in the middle of iPhone 6
This issue affects the compact height size class.
Before:
After:
=> Fixes #520 - Controls appearing in middle of screen on iPhone 6

Provenance/Game Library/PVGameImporter.h, Provenance/Game Library/PVGameImporter.m, Provenance/Game Library/PVGameLibraryViewController.m
Only trigger a library refresh if a rom lookup was triggered.
I've added 1888 nes/snes games to Provenance on an iPhone 6 and it would take 38 seconds to be responsive on launch. Now it's immediate.
I'm not sure why we run the game importer for each ROM that is already on the library, but the finish handler was called for each of those, which would trigger a library refresh (which can block the main thread for almost a second). I've modified the code to only refresh the library if the importer actually fetched new data for that ROM.
Library refresh speed can still be improved, but less than a second sounds OK to me right now.
=> Speed up app launch (specially on large libraries)

Provenance/Categories/UIDevice+Hardware.h, Provenance/Categories/UIDevice+Hardware.m, Provenance/Controller/PVControllerViewController.m
I converted the "isIphone7or7Plus" method to be a more general "hasTapticMotor" method and added the new model ID's for the iPhone 8, iPhone 8 Plus and iPhone X.
=> Use Taptic Engine for iPhone 8 and iPhone X

Mednafen/MednafenGameCore.mm, Mednafen/mednafen/state.cpp, PVSupport/PVSupport/PVEmulatorCore.h, PVSupport/PVSupport/PVEmulatorCore.m, Provenance/Emulator/PVEmulatorViewController.m, Provenance/Emulator/PVGLViewController.m, Provenance/Resources/shader_crt_fragment.glsl, ProvenanceTV/Resources/shader_crt_fragment.glsl
Posting this PR for consideration as discussed in #566 
Renderer will now function correctly when an emulator core does not write its final image to the top-left of the frame buffer, as is the case with PSX in Mednafen. As a result, I've removed the "wideScreen" flag as I believe that was hack to try and correct this behavior.
Cores can now implement double buffering and return YES from isDoubleBuffered to have the renderer take advantage of that fact and render in parallel to the emulation when needed. Mednafen now has double buffering implemented.
Replaced the mednafenCoreTiming hack with a call to setGameSpeed each frame as this will ensure that gameInterval stays in sync and it seems to fix various speed issues I was getting with PSX emulation.
Added some NULL checks to fix crashes I …
=> Mednafen improvements

ProvenanceTV/Base.lproj/Provenance.storyboard
Just a small fix reverting the background of the controller selection background to its default color. This default color is then compatible with both the light and the dark theme. See attached screenshots.
Hope you don't mind me just doing this small fix 🙂.
| | Before | After |
|:---:|:---:|:---:|
| Light | ![simulator screen shot - apple tv - 2018-03-31 at 20 05 35](https://user-images.githubusercontent.com/342095/38166158-8a19bfae-351f-11e8-9437-2c09cbfe15fd.png) | ![simulator screen shot - apple tv - 2018-03-31 at 20 07 25](https://user-images.githubusercontent.com/342095/38166159-8a32dc00-351f-11e8-9b5b-f89b35d504d7.png) |
| Dark | ![simulator screen shot - apple tv - 2018-03-31 at 20 05 09](https://user-images.githubusercontent.com/342095/38166157-89ff6c6c-351f-11e8-9f13-d2b0be834be5 …
=> [tvOS] Fix background of controller selection in settings

Provenance/Game Library/UI/PVGameLibraryViewController.swift
I told @Jasarien on discord about a crash when launching a game, and proposed a fix. He then committed the fix (379023f4). Unfortunately, I found it still crashes in some circumstances and have come up with a better fix. Also, I applied the fix to not just Recently Saved, but also to Recently Played.
Btw, this is my first Pull Request ever.
----
The Recently Saved section only displays the last 6 items, but the user probably has way more states saved than that. So when the collectionView sections update, sometimes the Realm update notification wants to update items outside the first 6, but those items don't exist in the collectionView. This causes a crash.
To fix this, we filter the deletions, insertions, and modifications to only those within the first 6 items.
=> Fixes crash that can happen when launching a game.

Mednafen/PVMednafen.xcodeproj/project.pbxproj
I changed the PVMednafen project to use the same compiler flags for release builds as debug builds. In my testing it does not seem to affect performance.
I believe this was happening only on an iPhone XS Max. My iPhone 7 Plus on iOS 12 seems ok so not sure why this is device-specific
This fixes #1001
=> Mednafen: Fixes crash on disk operations like opening cd images for release build

Cores/Genesis-Plus-GX/PVGenesis/Core.plist
When the Core was updated to 1.7.4 this marker was left at the previous 1.7.1. This minor PR fixes this.
=> Correct Core version reported for Genesis Core.

Provenance/Emulator/PVEmulatorViewController.swift
Write out PNG's instead of JPEG's for the Screenshot function. Gets us all of the RGBA channels as a 8888 pixel type for much better quality images at a much smaller size. 
Ex. A Genesis Sonic 2 title screen Screenshot at 2048x1536 as PNG is 243KB whilst the original JPEG at 50% lossy compression is 344KB.
=> Update Screenshot function to write PNG instead of JPEG

PVSupport/PVSupport/PVEmulatorCore.m
Small change to prevent deadlocking when saving save state for the n64 mupenplus core.
I changed to use `dispatch_async` but is there any reason to keep `dispatch_sync`? I think its maybe because the mupencore creates its own thread group when doing the async save state process. I hope its not harmful to the other cores.
=> Prevent deadlocking when saving state for mupenplus64 core

Cores/Mednafen/MednafenGameCore.mm
Enable all Pce rendered scanlines for full raster support and default back to allow for run+select “soft reset” like on the real console. Leave CD-Rom Read speed tweak to 4x as is.
=> Switch Mednafen over to pcefast core

Provenance/Utilities/shaders/blit/blit_fragment.glsl
Minor precision tweaks to blit shader for squeezing out extra bit of GPU performance on the lower end of the supported iOS hardware stack such as the iPad Air 1 by setting to lowp instead of mediump/highp.
=> tweak precision for blit shader

Provenance/Game Library/UI/GameLaunchingViewController.swift
Opt-out of the new card style modals on iOS 13 because the swipe-to-dismiss behavior interferes with the controls, and I'm pretty sure swipe-to-dismiss also prevents proper cleanup / save states.
I'm guessing there are other places in the app that might need a similar treatment, but so far this is the only one I've noticed where it's definitely needed.
Fixes #1236
=> Fix EmulatorVC modal presentation style on iOS 13

Cores/ProSystem/ProSystemGameCore.mm
Fixes tvOS issue with Apple Remote assuming it is always controller 1 and clobbering the inputs of the actual controller 1.
=> tvOS Apple Remote clobbering controller 1 inputs.

Provenance/Emulator/PVEmulatorViewController.swift
- Changed UIFont.systemFont to monospacedDigitSytemFont for more spatially stable text layout in the FPS Counter overlay.
- added in fpsLabel.isOpaque = true to help cut down on alpha blending calls for slower hardware.
- removed init of fpsLabel.text as it gets blown away later anyways.
First stage of improving the FPS counter functionality and performance for > 60.0Hz devices.
None.
=> Update FPS Counter font and performance items.

Provenance.xcodeproj/project.pbxproj, Provenance/Emulator/PVEmulatorViewController~iOS.swift, Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
This PR reverts the alert when hitting pause in game to the default Apple alert, it also swaps the 'alert' for an 'actionSheet' which presents from the bottom, separating alerts from other functions.
Not noticed but it also swaps ALAssetLibrary to PHPhotoLibrary, fixing deprecations and improving support for iOS 12+
No related tickets, discussion was between Sev and myself
=> Reverted custom emulator options alert update

Provenance/Controller/PVControllerManager.swift, Provenance/Emulator/PVEmulatorViewController.swift, Provenance/PVAppDelegate.swift
* Handle reconnection of Steam controllers transparently 
* Allow using the Steam controller to navigate the UI (on tvOS)
* Restore Steam button combinations to toggle controls (they were removed from the library):
* Steam + left pad click: toggle requiring click for input on left pad 
* Steam + right pad click: toggle requiring click for input on right pad 
* Steam + d-pad click: toggle d-pad and left trackpad mapping
* Use paused handler for all controllers except apple remote
* This allows the controller menu button to work on MFi/Xbox/PS4 controllers too
I've tested the following on iOS and tvOS 13.3:
* Steam Controller is detected automatically after it reconnects
* Steam Controller allows navigating the UI on tvOS
* Menu button behaves correctly on Steam Controller, Apple Remote, …
=> Updates for SteamController v1.2

.github/workflows/autosquash.yml, .gitignore, .swiftlint.yml
Adds a GitHub action bot to automatically squash and merge approved pull requests
1. Code owners approvals meet setting for repo
2. Any required tests/checks in GitHub repo settings are passed
3. Pull request has the `autosquash` label
This action runs on PR open, update etc. It will only execute though if all pre-conditions are met which are configured in the settings from GitHub.
The GitHub API has a flag called 'mergable" which means there are no conflicts, all peer reviews and automation bots are passed etc. Basically, does the PR have a green checkmark.
If so, this bot will squash and merge the PR.
1. The history is maintained in the meta-comments
2. Squash is easier than rebase for XCode projects with Apple's shitty Xcode project format which is a pain in the butt to rebase
3. Why …
=> CI - Add autosquash and merge CI action

Provenance/Emulator/PVEmulatorViewController.swift
This pull request selects the current game speed when the game speed alert is displayed. By default the "Slow" option is selected, regardless of what the current state is.
With this change, "Normal" is selected when no game speed has been set. This is also useful when choosing "Game Speed" by accident instead of "Save States".
Look at the game speed UIAlertController.
Start a NES game and choose "Game State".
=> Set default game speed with preferredAction in alert

Provenance/Emulator/PVEmulatorViewController~tvOS.swift
Adds a space between "AnalogMode" to match the behaviour on iOS.
Open the action sheet when using a controller.
This change was already made for iOS: https://github.com/Provenance-Emu/Provenance/commit/435d60810b2afc3ac44344d30650af3e87f5d438.
=> Add space between AnalogMode

Provenance/Game Library/UI/PVGameMoreInfoViewController.swift
This pull request solves the problem of game descriptions on tvOS being truncated. Scrolling is enabled and and the scroll position animates to the top once the selected field changes.
In addition, iOS-specific scroll behaviour has been removed from the tvOS build as it did not function correctly.
Import a game with a long game description.
=> Fix game description scrolling on tvOS

Provenance/Settings/PVSettingsViewController.swift
This pull request ensures the "Settings" tab bar title appears correctly after navigating to some secondary level settings. Navigating to "Systems" or "Manage Conflicts" will change the tab bar title, it needs to be set again after navigating back.
Compare with the original [settings controller](https://github.com/Provenance-Emu/Provenance/blame/develop/ProvenanceTV/PVTVSettingsViewController.swift#L36), which seems to be unused.
Navigate to Settings, Systems and back again.
Before:
After:
Secondary settings menus are somewhat inconsistent, some change the tab bar title (Systems, Manage Conflicts) and some show the view controller title (Core Options, Licenses). The view controller title is problematic it is out of the safe zone and can be truncated. Should the tab bar title be changed …
=> Fix settings tab bar title

Provenance/User Interface/Themes/Theme.swift
This pull request applies the correct UITableView appearance for the `PVSettingsViewController` view and related views. Previously it only applied to the appearance view.
Open the settings.
Before:
After:
Is this the best way to apply the appearance to the `PVSettingsViewController`? The text colour for a Mupen64Plus setting still has the wrong text colour:
=> Fix iOS settings table appearance

Provenance/User Interface/Themes/Theme.swift
This pull request fixes an appearance deprecation warning. Removing the relevant code seems to have little effect, the colour changes only slightly.
Look at the colour of the settings headers.
Before:
After:
=> Fix UITableViewHeaderFooterView deprecation warning

Provenance/Settings/WebServerActivatorController.swift
This pull request fixes the layout of the web server alert when accessed via the settings. The style now matches the alert when initiated from the home screen.
Tap "Launch Web Server".
Before:
After:
=> Fix web server alert

Provenance/Emulator/CoreOptionsViewController.swift
This pull request adds spacing before the tick and removes the superfluous space after.
Before:
After:
=> Add spacing before tick

PVLibrary/PVLibrary/Importer/Services/GameImporter.swift
The data in the `openvgdb.sqlite` contains many errors from when the data was collected. HTML entities are still encoded and all paragraphs in the game descriptions were removed.
This PR decodes the HTML entities and restores paragraphs that had been removed.
HTML entities are removed by extending the String class, the [HTMLEntities](https://github.com/IBM-Swift/swift-html-entities) framework was tested but didn't seem worth it to add a whole framework. There are 2530 HTML entities in the game descriptions.
Paragraphs are restored by checking for a capital letter directly after a `.`, `!` or `?`, there must be at least a couple of normal letters after, this prevents false positives such as `U.S.`. There are a total of 6283 collapsed paragraphs in the game descriptions.
Import a game.
=> Clean game description during import

PVSupport/Logging/PVCocoaLumberJackLogging.m, Provenance.xcodeproj/project.pbxproj, Provenance/PVAppDelegate.swift
This pull request uses the `DDOSLogger` logger instead of the `DDTTYLogger` one to fix the following warning:
`CocoaLumberjack: Warning: Usage of DDTTYLogger detected when DDOSLogger is available and can be used! Please consider migrating to DDOSLogger.`
iOS 10 is required and the build target has been updated to reflect the [Building from Source](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/building-from-source) instructions.
The [XcodeColors](https://github.com/robbiehanson/XcodeColors) plugin no longer works so references to it were removed.
Check error logging.
=> Update CocoaLumberjack logger

PVSupport/PVSupport.xcodeproj/project.pbxproj, Provenance.xcodeproj/project.pbxproj
This pull request removes the NSLoggerSwift framework to fix the following warning:
`Class FPLLoggerBonjourDelegate is implemented in both...`
According to the [Carthage instructions](https://github.com/fpillet/NSLogger#carthage-install), only `NSLogger` or `NSLoggerSwift` should be included. There appear to be no `NSLoggerSwift` imports in the project.
=> Remove NSLoggerSwift framework

Provenance/User Interface/Themes/UIAlertController+Theming.swift
This pull request ensures the button colour doesn't change after being touched.
Fixes https://github.com/Provenance-Emu/Provenance/issues/1347https://github.com/Provenance-Emu/Provenance/issues/1347.
=> Fix button text colour after touch

Provenance/Emulator/CoreOptionsViewController.swift
This pull request uses the `display.description` variable as the SwitchRow subtitle if available (like with the [.multi ](https://github.com/dnicolson/Provenance/blob/101022af9eca763583f0ca99196ef079dd4ccdb8/Provenance/Emulator/CoreOptionsViewController.swift#L68)option).
It is dependent on QuickTableViewController v1.2.2 which includes https://github.com/bcylin/QuickTableViewController/pull/45 so Carthage must be updated.
Before:
After:
=> Fix SwitchRow subtitles

PVSupport/CoreOptions/CoreOptions.swift
This pull request fixes core option settings not being saved. Traversing sub-options did not work correctly and also `UserDefaults` was not called when getting sub-options.
Look at how the sub-options are stored.
Toggle the Core Options > Mupen64Plus > HW Lighting switch.
https://github.com/Provenance-Emu/Provenance/issues/1337
=> Fix core option sub-options

Provenance/Settings/Cells/SliderCell.swift
This pull request removes animation of slider cell values. Slider cells animate at the moment, when scrolling occurs it looks incorrect for a slider value to suddenly change.
Open settings and scroll down.
https://github.com/Provenance-Emu/Provenance/issues/1341
=> Remove slider cell animation

Provenance/Game Library/UI/GameLaunchingViewController.swift
I'm not really sure why this call is here, but removing it seems to fix
the rather strange issue #1066. Anyway, since the codePath where
`saveState == nil` doesn't ever run `view.isHidden = false` it seems
like this is an error, and I couldn't see any reason why it should be
there in the first place.
I've only tested this locally myself, so it would be nice to have some more testing, with different cores/games etc
Fixes #1066
=> Don't call view.isHidden on unloaded view, fixes #1066.

Cores/Mednafen/MednafenGameCore.mm
We should Default to using the full featured, and very cycle accurate, PCE core and not the PCE Fast engine.
Swaps from using PCE Fast for PC-Engine/TG16 to the accurate version called PCE.
=> Update Mednafen to use Accurate PCE Core.

Cores/Mupen64Plus/MupenOptions.swift
This pull adjusts the request Mupen64Plus settings in the following ways:
- "RICE" is replaced with "Rice Video" as per the [documentation](https://github.com/mupen64plus/mupen64plus-video-rice).
- The display title description was moved from "RSP Plugin" to "GFX Plugin".
Look at the Mupen64Plus core options.
The https://github.com/Provenance-Emu/Provenance/commit/accf48e8fd8784c9aae26ac394ac273748117740 move is assumed to be correct, feel free to revert.
=> Fix Mupen64Plus options

Provenance.xcodeproj/project.pbxproj, Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift, Provenance/Game Library/UI/PVConflictViewController.swift, Provenance/PVAppDelegate.swift, Provenance/Settings/PVSettingsViewController.swift, Provenance/Utilities/PVGameLibraryUpdatesController.swift
This PR moves most of the handling of scanning directories, importing files and handling conflicts out of PVGameLibraryViewController, making that VC a bit less bloated and also fixes some synchronisation issues between views.
The new PVGameLibraryUpdatesController is now responsible for everything above, so that's a good way to start. Then it emits some events when UI needs to be shown to the user, so the UI-parts are still handled in the GameLibraryVC.
Make sure that imports still work as expected, including resolving conflicts.
The base motivation for this is to make the PVGameLibraryViewController more manageable, and move stuff out of it, so this is a small step in that direction.
Probably fixes #833 (due to better synchronization)
Fixes #1339 (due to different logic)
=> Handle updates to game-library outside of PVGameLibraryViewController

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
This pull request prevents the search text field from collapsing after changing orientation.
Change orientation from landscape to portrait.
https://github.com/Provenance-Emu/Provenance/issues/1379
The search field will no longer appear as this:
=> Fix search field after orientation change

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift, ProvenanceTV/PVTVTabBarController.swift
This pull request fixes the [Simulator conditional](https://stackoverflow.com/questions/36180702/whats-wrong-with-my-if-target-os-simulator-code-for-realm-path-definition) and applies it to all the keyboard shortcuts.
Check the keyboard shortcuts in the Simulator.
=> Fix keyboard shortcuts in the Simulator

Provenance/Emulator/CoreOptionsViewController.swift, Provenance/User Interface/Themes/UIAlertController+Theming.swift
This pull request fixes a crash on iPad when a UIAlert was invoked in core options. Alerts are now placed near the relevant table cell. Some theme code was removed to fix a height issue.
Open a UIAlert in core options with an iPad device.
After the crash fix:
After the theme fix:
Does the removal of the `viewDidLayoutSubviews` override cause any issues?
=> Fix core options crash on iPad

Provenance/Settings/PVSettingsViewController.swift
The order of items under core options differs between iOS and tvOS. This is because it is dependent on a class list being [generated](https://github.com/Provenance-Emu/Provenance/blob/develop/PVLibrary/PVLibrary/Configuration/PVEmulatorConfiguration+Frameworks.swift#L22) from arbitrary memory locations. The list of systems is also [sorted](https://github.com/dnicolson/Provenance/blob/develop/Provenance/Settings/SystemSettings/SystemsSettingsTableViewController.swift#L20) in a similar way.
Check the order of core options on iOS and tvOS.
=> Make core options order consistent across tvOS and iOS

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
This pull request fixes the alignment of the right corner badge after changing orientation.
The `topRightBadgeTrailingConstraint` and the `topRightBadgeTopConstraint` values can be set incorrectly in the [updateImageConstraints](https://github.com/Provenance-Emu/Provenance/blob/develop/Provenance/Game%20Library/UI/Game%20Library/Reusable%20Views/PVGameLibraryCollectionViewCell.swift#L959) method due to incorrect `bounds` values in the [contentClippingRect](https://github.com/Provenance-Emu/Provenance/blob/develop/Provenance/Game%20Library/UI/Game%20Library/Reusable%20Views/PVGameLibraryCollectionViewCell.swift#L178) method while the UI is busy. Unlike the previous pull request (https://github.com/Provenance-Emu/Provenance/pull/1384) the whole data is not reloaded.
Change orientation from …
=> Fix corner badge after orientation change

Provenance/Settings/Cells/SliderCell.swift
This pull request adjusts the slider length so it does not overlap with the label.
Interact a the slider in the settings.
Most of the credit is due to the work of @antiquebeta, only a few changes were made in this file from the original [pull request](https://github.com/Provenance-Emu/Provenance/pull/1265/files#diff-e0eedeff11a15cfb1d2fc017bda22b72R131):
- The leading constraint was changed from `20` to `15`.
- The async UI updates were removed.
- A `heightAnchor` constraint was added to suppress a warning that other top/bottom constraints failed to suppress.
Before:
After:
=> Adjust slider length for label in SliderCell

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
This pull request prevents an NSLayoutConstraint warning from appearing in the console.
Inspect related constraints.
Test that `PVGameLibraryCollectionViewCell` games appear correctly.
https://github.com/Provenance-Emu/Provenance/issues/1344
=> Fix NSLayoutConstraint warning

Provenance/Emulator/CoreOptionsViewController.swift
This pull request specifies the same cell class as used in the top-level settings to use the same styles.
Check core options and the PVSwitchCell class. The HW Lighting and GFX Plugin cells have matching colours.
Check Mupen64Plus core options.
https://github.com/Provenance-Emu/Provenance/issues/1342
=> Fix core option SwitchRow colours

Provenance/Emulator/CoreOptionsViewController.swift
This pull request sets the `selectionStyle` to `none` after tapping a multi core option.
Tap a core option.
This [issue](https://github.com/bcylin/QuickTableViewController/issues/39) was used as a reference.
=> Fix core option selectionStyle

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
This pull request reverts https://github.com/Provenance-Emu/Provenance/pull/1383 due to issues with iOS 11 and 12.
It is not clear what causes the search field to collapse (https://github.com/Provenance-Emu/Provenance/issues/1379), the problem doesn't occur if the `collectionView` is not added to the subview or if a large height constraint is applied to the `searchBar`.
=> Revert search field fix

PVLibrary/PVLibrary/Domain/BIOS.swift
This pull request fixes the file check for the existence of a BIOS. Previously BIOSes that did not exist would have an MD5 error and BIOSes that existed had the wrong status.
Upload a BIOS and check Systems in Settings.
=> Fix BIOS status

Cores/Mednafen/MednafenGameCore.mm, Cores/Mednafen/mednafen/src/pce/pce.cpp
This PR restores the previously missing first 3 scanlines in the PCE module.
=> Pce scanline restore

PVLibrary/PVLibrary/RealmPlatform/Entities/Files/PVFile.swift
This fixes an issue where there's a mismatch between location of save states and their images and what's recorded in Realm. In short we're trying to create a relative path to store in the database, but trying to resolve against the `iCloud` root (which isn't even available on tvOS.
Start any game, create a save state, close provenance and load the save again.
Would be nice to get this tested on both iOS and tvOS
Originally discussed here: https://discord.com/channels/421819941835243520/426555484221341708/722498320794124349
Couldn't find any, but I assume more people has seen this bug, since it basically breaks save states on tvOS
=> Make sure we use the correct root when creating relative paths

PVLibrary/PVLibrary/Resources/systems.plist
Make SuperGrafx games unique with the .sgx extension and no longer use the .pce as a catch-all.
This will result in less of a chance with the GameImporter throwing conflicts as there are only 5 games for the entire system.
=> Update systems.plist - Make SuperGrafx games unique with the .sgx extension.

.github/ISSUE_TEMPLATE/bug-report.md
This pull request adds iOS 14 to the issue template.
-----
[View rendered .github/ISSUE_TEMPLATE/bug-report.md](https://github.com/dnicolson/Provenance/blob/patch-1/.github/ISSUE_TEMPLATE/bug-report.md)
=> Add iOS 14 to issue template

Provenance/Settings/PVSettingsViewController.swift
This pull request slightly increases the settings table row height. If a cell has a subtitle the vertical padding can look off.
Before:
After:
=> Increase settings tvOS row height

Cores/Genesis-Plus-GX/PVGenesis/Genesis/PVGenesisEmulatorCore.m, PVSupport/Settings/PVSettingsModel.swift, Provenance.xcworkspace/xcshareddata/xcschemes/Provenance-Release.xcscheme, Provenance.xcworkspace/xcshareddata/xcschemes/ProvenanceTV-Release.xcscheme, Provenance/Emulator/PVGLViewController.m
Reverts Provenance-Emu/Provenance#1454 to make sure the iOS build still works.
=> Revert "Project Release Scheme Optimization and Performance tweaks"

Provenance/Game Library/UI/GameLaunchingViewController.swift, Provenance/Settings/PVSettingsViewController.swift
This pull request sorts of the order of the cores so that they display in the same order on tvOS and iOS. At the moment for NES games the order of the "Mednafen" and "FCEUX" cores is different.
Additionally, the sorting that was applied in #1397 has been changed to make it consistent with [original sorting](https://github.com/dnicolson/Provenance/blob/sort-cores-before-game/Provenance/Settings/PVCoresTableViewContorller.swift#L17) by using the `projectName` key.
Check that the order of the cores when starting a NES game are consistent on tvOS and iOS.
=> Sort cores displayed when starting a game

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController+CollectionView.swift, Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift, Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift
This pull request enables the collapse buttons on tvOS, similar to how they function on iOS. It was originally planned to remove the non-functional buttons in https://github.com/Provenance-Emu/Provenance/pull/1460, after some discussion adding focus functionality was decided instead.
Look at how the focus state is changed.
Test with at least a few consoles that have ROMS with less than 7, 7, and more than 7 items.
Different focus approaches were considered:
- Originally the focus was automatically shifted from the header to the button. This unfortunately rendered some section items inaccessible as the focus would only go down from the button which required at least 7 items below for a focus hit.
- Letting the user focus on the collapse button by using the right key (not a swipe), this …
=> Make collapse buttons focusable on tvOS

PVLibrary/PVLibrary.xcodeproj/project.pbxproj
Happy new year, everyone! 🎈 
Compiling on an M1 machine wasn’t possible for both iOS device and simulator: "Building for iOS, but the linked and embedded framework 'RxRealm.framework' was built for iOS + iOS Simulator".
Enabling workspace validation makes it work.
=> Enable VALIDATE_WORKSPACE for PVLibrary

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Hello, it's a me again. 👋 
I saw #1436 where the app crashes on iPads when showing an action sheet.
This is a funny tidbit everybody has run into before once at least when using UIImagePicker on iPads (and how action sheets are being presented on iPad). Unlike on iPhones, on iPads it is being presented within a popover and popovers need certain information about the environment they're being presented in (where should the arrow point to, which view is the source of the interaction...). 
For a better explanation, check out my comment [here](https://github.com/Provenance-Emu/Provenance/issues/1436#issuecomment-753530659).
=> Fix action sheet crash on iPad

Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/HISTORY.txt, Cores/Genesis-Plus-GX/PVGenesis/Genesis/GenesisCore/genplusgx_source/sound/ym2413.c
Sync up to GenesisPlusGX Mainline 8acd9def6d1fd7d10add309982d625d3ecd18ca8
- [Core/Sound] fixed MAME YM2413 core EG updates being 2x faster after EG resolution change and improved EG increment steps accuracy (verified on YM2413 real hardware, cf. https://www.smspower.org/Development/YM2413ReverseEngineeringNotes2015-03-20)
- [Core/Sound] improved MAME YM2413 EG transitions accuracy (verified against https://github.com/nukeykt/Nuked-OPLL/blob/master/opll.c)
=> Core - Update: Sync up to GenesisPlusGX Mainline 8acd9de

Provenance/Game Library/UI/GameLaunchingViewController.swift
This pull request reduces the size of the switch so that the vertical margins are more equal.
Start a game on iOS that has a saved state.
Before:
After:
=> Adjust UISwitch size

Provenance/Emulator/PVEmulatorViewController+Saves.swift
This pull request restores the functionality of the "Reset" menu item if there is less than one minute of gameplay. Otherwise, a "Latest manual save state is too recent to make a new auto save" message will be logged and no reset will be performed.
Use the "Reset" menu item within 1 minute of gameplay.
The issue appears to be introduced in https://github.com/Provenance-Emu/Provenance/pull/1493 because https://github.com/provenance-emu/Provenance/blob/031592a/Provenance/Emulator/PVEmulatorViewController+PauseMenu.swift#L177 is unreachable.
=> Fix reset menu for gameplay of less than 1 minute

Provenance/Emulator/PVEmulatorViewController.swift
This partially reverts #1473 since that broke the pause-button behaviour (for me at least).
This PR also refactors the code related to pause/menu-button handling a bit, and uses the new `buttonMenu` API:s (if available).
I've tested on ATV 4K (tvOS 14.7) with a DS4 and the Siri remote, would be nice with some testing with other combos as well. Just verify that the pause/menu/start button brings up the provenance menu and pauses the game as expected.
It would be extra nice if @dnicolson could verify that this does indeed work, so that we're not breaking things for each other 😄
=> Fix pause-button on tvOS

Provenance/Emulator/PVEmulatorViewController.swift
So, I messed up in #1570 and didn't add a proper check for iOS 13.0 availability, here it is.
Also going to look into just getting a GitHub-action that builds for iOS and tvOS, as a bare-minimum check :) 
Fixes #1574
=> Add missing iOS 13.0 to #availability check

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
Update Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift
Adding a proper else case to remove default string
Fix search field on iOS 11 and later
=> Fix game titles if Show Game Titles is enabled

Provenance/Settings/PVSettingsViewController.swift
Present a newly updated Text that clarifies the process and steps to take to successfully refresh the game library artwork and game information in the Ui Dialog that is presented when a user enters Settings -> Refresh Game Library.
This PR is in support of the 2.0.1 release milestone and the various GameLibrary fixes that have been addressed.
=> Clarify Refresh Game Library Ui Dialog text

README.md
This pull request adjusts the `h1` style to appear as light or dark depending on how it is viewed. Editing the file in Typora now appears as white and in Gitfox appears as light or dark depending on if Dark Mode is enabled. Also, on GitHub the black styling appears to have no effect.
=> Adjust README heading to support Dark Mode

Cores/Mupen64Plus/MupenGameCore.m
This changes the EAGLContext bestContext block #if ! statements that are currently (probably) not allowing the Mupen N64 core to render any video.
@JoeMatt will need to confirm that this is the right solution of course.
=> (Possible) Mupen N64 Core fix for tvOS/iOS

Provenance/Utilities/shaders/crt/crt_fragment.glsl
Update the TVL(ines) parameter in the CRT shader from 350.0 to 800.0 to match a Sony BVM and to also help reduce the moirée artifacts that we see on the AppleTV at UHD / 4K.
=> Update TVL in crt_fragment.glsl to reduce moirée effects at UHD

Cores/PPSSPP/PVPPSSPP.xcodeproj/project.pbxproj
Uses relative to group instead
Fixes build for tvOS
build and run on tvOS
=> Remove absolute path to file from .xcodeproj

Cores/Mednafen/PVMednafen.xcodeproj/project.pbxproj, Cores/Mupen64Plus/MupenGameCore.m, PVLibrary/PVLibrary/Database/OESQLiteDatabase.m, PVLibrary/PVLibrary/NSExtensions/NSFileManager+Hashing.m, PVSupport/DebugUtils.h, PVSupport/EmulatorCore/PVEmulatorCore.m, PVSupport/PVSupport/Audio/CARingBuffer/CAAtomic.h, PVSupport/PVSupport/Audio/CARingBuffer/CARingBuffer.cpp, PVSupport/PVSupport/Audio/CARingBuffer/CARingBuffer.h, PVSupport/PVSupport/Audio/TPCircularBuffer.c, PVSupport/PVSupport/NSFileManager+OEHashingAdditions.m, Provenance/Categories/UIImage+ImageEffects.m, Provenance/Emulator/PVGLViewController.m, Provenance/Provenance-Info.plist, ProvenanceTV/zh-Hans.lproj/Info.plist
1. Remove m68k from hwcpu
2. Make a new libhwcpu-m68k
3. Don't compile that lib
Making a new lib in case I need to roll that back.
This should speed up release compiles a lot.
Bonus
Created LIKELY/UNLIKELY macros, similar to cores like mednafen use, to hint at how to optimize boolean logic operations and loops
=> Speedup Mednafen compile, and LIKELY compiler hints

.gitmodules
This pull request fixes the following Git errors when running `git submodule status`:
`fatal: no submodule mapping found in .gitmodules for path 'Cores/Flycast/flycast'`
`fatal: no submodule mapping found in .gitmodules for path 'Cores/PPSSPP/cmake/assets/debugger'`
The `Cores/Flycast/flycast` submodule was defined twice and the second error was resolved with the following command:
`git rm --cached Cores/PPSSPP/cmake/assets/debugger`
=> Fix submodule errors

Provenance/Emulator/PVEmulatorViewController.swift, Provenance/Game Library/UI/QuickTableViewController/QuickTableViewController.swift, Provenance/Provenance-Info.plist
* force DarkMode (in the Info.plist) so if we are running on a device *not* in DarkMode app will look correct.
* Use a insetGrouped style for UITableView (on iOS 13+) to match new style.
* Use the `HOME` button on a game controller (iOS 14+)
=> Ios 13 UX tweaks

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift, Provenance/PVAppDelegate.swift, ProvenanceTV/Story Boards/en.lproj/Provenance.storyboard
Remove all the Focus Engine problems on tvOS main screen
you can now select all the Bar Button Items!
see issue #1456
I did this by removing the UITabBarController and made the main screen on tvOS *just like* the main screen on iOS.
*except* I added a BarButtonItem to bring up the Search page.
run on tvOS and make sure main UX functions
make sure iOS version still runs and builds
Issue #1456
=> fix tvOS focus hell

Provenance/Emulator/PVGLViewController/PVMetalViewController.m
-Fix Red/Blue color swap when using OpenGL cores
-Avoid OpenGL init work for cores not using OpenGL
=> [Metal] Format and size bugfixes

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Matches the size of the Pv Branding to not exceed the CapHeight on tvOS.
=> Match Provenance branding size to capHeight on tvOS

Provenance/Emulator/PVGLViewController/PVMetalViewController.m
Fixes CPU render and from OpenGL core paths to account for the `emulatorCore.screenRect.origin` when doing the copy into a MTLTexture.
This fixes the issue with the TurboGrafx-16 Core having the view shifted down incorrectly. 
I also briefly tested NES, N64 and Genesis cores to make sure there weren't any obvious regressions.
=> Fix Metal input texture copy to account for cores using an offset origin

Cores/Genesis-Plus-GX/PVGenesis/Genesis/PVGenesisEmulatorCore.m, Provenance/Settings/PVSettingsViewController.swift
Restore Genesis Start Button mapping to Right Trigger on M30 to sync up to the other implementations.
=> M30 fixes and clarifications

Provenance.xcodeproj/project.pbxproj
This extra Metal compiler build option gets us a nice 200% (or more in some cases) speed-up and allows for running the full MTL CRT Shader at 60fps in UHD.
=> Enable MTL fast math support

PVLibrary/PVLibrary/Resources/systems.plist
Updates Atari8Bit bios sizes (and uppercases `ATARIBAS.ROM`)
n/a
Import Atari8Bit bioses - sizes should match. 
I built the latest ([3b77a7c0dffc3c388912fa6c42a132b9d8bcda81](https://github.com/Provenance-Emu/Provenance/commit/3b77a7c0dffc3c388912fa6c42a132b9d8bcda81)) commit and saw that importing Atari8Bit bioses result in size mismatch, even though checksums match. It wasn't a problem on iOS build, as I could just change it in `default.realm`, but the problem got bigger on tvOS, where I couldn't find the database. Now I'm stuck without Atari8Bit on tvOS, hence this PR.
n/a
n/a
n/a
=> Update Atari8bit bios sizes

Cores/snes9x/PVSNES/SNES/PVSNESEmulatorCore.mm
Quick formatting fix to restore MFI controls to the snes9x core. 
This should close #1848
=> Update SNES9x's PVSNESEmulatorCore.mm to fix MFI Controls

Provenance/Emulator/Shaders/blit_ps.metal
MTL refactor to use half as opposed to floats in the fragment shaders
Ongoing PR to refactor the Provenance MTL fragment shaders to default to using halfs as opposed to floats for better power efficiency and a performance increase on mobile devices.
=> Update blit_ps.metal to use Halfs

Provenance/Utilities/PVLogViewController.xib
This pull request slightly reduces the width of the log buttons to allow the "Select File" button to appear properly.
Before:
After:
=> Reduce width of log buttons

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
This pull request increases the perceived height of the navigation bar by adding a constraint to the game library view and also by extending a navigation bar subview. It [doesn't seem possible](https://stackoverflow.com/a/47916936/2693925) anymore to change the height of the navigation bar directly. It is possible to make some changes in the navigation bar in the `viewDidLayoutSubviews` method, but it doesn't seem possible to change the height.
Before:
After:
=> Extend navigation bar on tvOS

Provenance/Settings/Cells/PVSliderCell.swift, Provenance/Settings/Cells/PVSwitchCell.swift, Provenance/Settings/PVSettingsViewController.swift
This pull request removes some unused tvOS code (`PVSliderCell`), and some seemingly unneeded code (`PVSwitchCell`) and makes some improvements to cell font sizing on tvOS.
Before:
After:
=> Fix tvOS styling

ProvenanceTV/TVAlertController.swift
This pull request fixes two constraint warnings, the height one was fixed with d4a2591 but was superseded by c6b7839 which fixes both. The UIStackView issue is discussed [here](https://stackoverflow.com/questions/33073127/nested-uistackviews-broken-constraints).
=> Fix TVAlertController button height constraint warning

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift, Provenance/Game Library/UI/Game Library/Reusable Views/en.lproj/PVGameLibraryCollectionViewCell.xib, Provenance/Game Library/UI/Game Library/Reusable Views/it.lproj/PVGameLibraryCollectionViewCell.xib, Provenance/Game Library/UI/Game Library/Reusable Views/ja.lproj/PVGameLibraryCollectionViewCell.xib, Provenance/Game Library/UI/Game Library/Reusable Views/ru.lproj/PVGameLibraryCollectionViewCell.xib, Provenance/Game Library/UI/Game Library/Reusable Views/zh-Hans.lproj/PVGameLibraryCollectionViewCell.xib, Provenance/User Interface/en.lproj/Provenance.storyboard, Provenance/User Interface/en.lproj/SaveStates.storyboard, Provenance/User Interface/es.lproj/Provenance.storyboard, Provenance/User Interface/es.lproj/SaveStates.storyboard, Provenance/User Interface/it.lproj/Provenance.storyboard, Provenance/User Interface/it.lproj/SaveStates.storyboard, Provenance/User Interface/ja.lproj/Provenance.storyboard, Provenance/User Interface/ja.lproj/SaveStates.storyboard, Provenance/User Interface/nl.lproj/Provenance.storyboard, Provenance/User Interface/nl.lproj/SaveStates.storyboard, Provenance/User Interface/ru.lproj/Provenance.storyboard, Provenance/User Interface/ru.lproj/SaveStates.storyboard, ProvenanceTV/TVAlertController.swift
This pull request removes superfluous styles and uses system defaults where possible as iOS 13 has support for Dark Mode.
- The cell background was removed with code as it is the same as the view background, the red background was also removed from the storyboard. Missing games still appear with a red background.
- iOS 13 deprecates `groupTableViewBackground` in favor of `systemGroupedBackgroundColor`.
- The EN storyboard was copied to all other locales as the differences were negligible except for ES, which was missing some things.
=> Use system styling in storyboards

Provenance/Game Library/UI/GameLaunchingViewController.swift, ProvenanceTV/TVAlertController.swift
This pull request uses `TVAlertController` for all alerts instead of ignoring `.alert` styles.
There doesn't seem to be any reason not to use this everywhere, system alerts still work and it seems to work fine with:
- Launch Web Server
- Refresh Game Library
- Empty Image Cache
- Save State Detected (a small change in 6da54ef)
- Delete Save State
=> Use TVAlertController everywhere

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift, Provenance/User Interface/en.lproj/Default.xib, Provenance/User Interface/en.lproj/Provenance.storyboard, Provenance/User Interface/es.lproj/Default.xib, Provenance/User Interface/es.lproj/Provenance.storyboard, Provenance/User Interface/it.lproj/Default.xib, Provenance/User Interface/it.lproj/Provenance.storyboard, Provenance/User Interface/ja.lproj/Default.xib, Provenance/User Interface/ja.lproj/Provenance.storyboard, Provenance/User Interface/nl.lproj/Default.xib, Provenance/User Interface/nl.lproj/Provenance.storyboard, Provenance/User Interface/pt-BR.lproj/Default.xib, Provenance/User Interface/ru.lproj/Default.xib, Provenance/User Interface/ru.lproj/Provenance.storyboard, Provenance/User Interface/zh-Hans.lproj/Default.xib
This pull request uses the system gear icon for the settings button in the loading view and uses the default size in the game library view for consistency.
=> Tweak settings button and navigation bar fixes

Provenance/Controller/PVControllerSelectionViewController.swift
This pull request prevents dismissing the modal without making a selection which leaves the cell with a tint. Dismissing the modal or selecting "Not Playing" also has the same effect.
=> Fix tint after using the cancel action when selecting a controller

PVLibrary/PVLibrary/Database/PVGameLibrary.swift, Provenance/NewUI/Consoles/ConsoleGamesView.swift, Provenance/NewUI/Consoles/ConsolesWrapperView.swift, Provenance/NewUI/PVRootViewController+DelegateMethods.swift, Provenance/NewUI/PVRootViewController.swift, Provenance/PVAppDelegate.swift
This updates the SwiftUI flow in two small-ish ways:
* the landing screen will now be the first console in the console page view if any consoles with games are available. Otherwise, it will still default to the Home view.
* reduces the open width of the side menu a bit. See attached screenshot.
This stems from conversations about the usability of this flow now that it's in some peoples hands.
=> SwiftUI flow — make landing screen the console carousel if any consoles available, reduce side menu open width

PVSupport/Sources/PVSupport/Settings/PVSettingsModel.swift, Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController+CollectionView.swift, Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Add in large Game Art Setting to allow the user to toggle between 6 columns of Title Artwork, or 7. 
(This defaults to 7 which results in smaller Title Artwork.)
=> Add Larger Game Library Artwork Display Option for tvOS

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
This (slight) tweak restores the original GameCollection Library View margins, thereby once again allowing for up to 7 titles on tvOS.  Moved the layout.sectionInsetReference addition that broke all of this on tvOS back into an already existing #if os(iOS) section.
Also reduced the Header Height extension by @dnicolson from 49px back down to 20px in order to have more real-estate for the Library view on tvOS.
=> Update PVGameLibraryViewController.swift - tvOS Header and Margin tweaks.

PVSupport/PVSupport.xcodeproj/project.pbxproj, PVSupport/Sources/PVSupport/Settings/PVSettingsModel.swift, PVSupport/Sources/PVSupport/Settings/ThemeOption.swift, Provenance/Controller/PViCadeControllerViewController.swift, Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift, Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift, Provenance/PVAppDelegate.swift, Provenance/Provenance-Info.plist, Provenance/Settings/Cells/PVSliderCell.swift, Provenance/Settings/Cells/PVSwitchCell.swift, Provenance/Settings/Custom Rows/SettingsOptionRow.swift, Provenance/Settings/PVSettingsViewController.swift, Provenance/Settings/SystemSettings/SystemSettingsCell.swift, Provenance/Settings/SystemSettings/SystemSettingsHeaderCell.swift, Provenance/Settings/SystemSettings/SystemsSettingsTableViewController.swift, Provenance/User Interface/Themes/Theme.swift, Provenance/Utilities/PVLogViewController.xib
This pull request removes a lot of redundant dark and light theme code by leveraging the appearance defaults in iOS 13+. Only a minimal set of changes were made to the Theme file, much more code can also be removed.
This works by setting the `overrideUserInterfaceStyle` on launch and provides a setting option to switch themes. The light theme can probably be improved upon in terms of design choices.
https://user-images.githubusercontent.com/2276355/204145362-87ebd85d-3ef7-4c1d-bf4d-39b419e1b0c4.mov
=> Add light theme for iOS

Provenance/Game Library/UI/PVGameMoreInfoViewController.swift
tvOS Only - This allows the user to use a double click on the controller/remote to view the Back of the Box artwork when in the GameInfo view.  
This PR also removes the scrolling/editing options and sets the Game Description Text to a fixed 24 System Font for better readability without having to scroll when viewing large bodies of text.
=> Update PVGameMoreInfoViewController.swift - tvOS usability and Back of the Box support.

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift
This pull request adjusts the position of the game library header separators.
=> Prevent game library header separators from disappearing

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibrarySectionHeaderView.swift
Propagates @dnicolson's #2033 fix for the Section headers disappearing to tvOS as well. Tested and works.
=> Section header disappearing fix for tvOS from #2033

PVLibrary/PVLibrary/Importer/Services/GameImporter.swift
This pull request fixes the character encoding of game imports. For example, "Pokémon" appears as "PokÃ©mon".
The issue appeared after https://github.com/Provenance-Emu/Provenance/pull/1319, it is not clear why the text is no longer encoded with UTF-8. The database is encoded in UTF-8:
```
sqlite3 openvgdb.sqlite
SQLite version 3.39.4 2022-09-07 20:51:41
Enter ".help" for usage hints.
sqlite> pragma encoding;
UTF-8
```
=> Fix game description character encoding

Provenance/Game Library/UI/GameLaunchingViewController.swift
This pull request adds a cancel action to the save game alert, this allows dismissing the modal by tapping outside of it.
=> Add cancel action to save state alert

Provenance/Game Library/UI/CollectionViewInACell/CollectionViewInCollectionViewCell.swift
This pull request fixes the following warning:
```
2022-12-15 17:16:01.327562+0100 Provenance[69893:59795708] The behavior of the UICollectionViewFlowLayout is not defined because:
2022-12-15 17:16:01.327708+0100 Provenance[69893:59795708] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2022-12-15 17:16:01.328053+0100 Provenance[69893:59795708] The relevant UICollectionViewFlowLayout instance is <Provenance.CenterViewFlowLayout: 0x125111e50>, and it is attached to <UICollectionView: 0x12601e800; frame = (0 0; 1920 244); gestureRecognizers = <NSArray: 0x600003660030>; layer = <CALayer: 0x600003ed09e0>; contentOffset: {-80, 0}; contentSize: {0, 0}; adjustedContentInset: {0, …
```
=> Fix UICollectionViewFlowLayout warning

Provenance/Game Library/UI/Game Library/Reusable Views/PVGameLibraryCollectionViewCell.swift, Provenance/Game Library/UI/PVGameMoreInfoViewController.swift, Provenance/Settings/PVSettingsViewController.swift
This pull request fixes the missing artwork game cell background colors, the ability to cancel the theme change alert makes it more consistent with other alerts.
Before and afters:
=> Fix missing artwork background

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
This pull request prevents a crash when using the keyboard on an iPad, makes search input immediately focused and resolves `UIKeyCommand` deprecation warnings.
It's not clear if `discoverabilityTitle` is needed on tvOS anymore, but it's still a property.
=> Fix keyboard input

Provenance/Controller/PVControllerViewController.swift
This pull request fixes the following error when building a Catalyst target:
```
Type 'UIDevice' has no member 'hasTapticMotor'
```
=> Fix Catalyst build

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
This pull request prevents the iOS alert from using the [.automatic](https://github.com/Provenance-Emu/Provenance/blame/28007c1/ProvenanceTV/TVAlertController.swift#L246) `modalPresentationStyle`.
I'm wondering if it's better to fix this in the `TVAlertController`? I don't know what is happening in Catalyst.
=> Fix import alert on iOS

Cores/Genesis-Plus-GX/PVGenesis/Genesis/PVGenesisEmulatorCore.m
This properly sets the Aspect Ratio for the Genesis Core in Pv.  Tested and confirmed with the 240P Monoscope pattern. This now displays a 1:1 matching Square.  Pv Integer mode now also scales accurately for the Genesis Core.
=> PVGenesis - Fix Genesis Aspect Ratio

Cores/PicoDrive/PicodriveGameCore.m
This properly sets the Aspect Ratio for the Sega 32X Core using PicoDrive in Pv.  Tested and confirmed with the 240P Monoscope pattern. This now displays a 1:1 matching Square.  Pv Integer mode now also scales accurately for the Genesis Core.
=> PVPicoDrive 32X - Fix Sega 32X Aspect Ratio

Provenance/Emulator/Shaders/Shaders/Metal/Filters/crt_filter_ps.metal
Adds in always-on Linear filtering for the MTL CRT Filter and fixed edge clamping behavior.
=> Update crt_filter_ps.metal - Metal version always uses Filtering for smoother edges and AA.

Cores/Play/PVPlayCore.xcodeproj/project.pbxproj, Cores/Play/PVPlayCore/Core/CGSH_Provenance_OGL.mm, Cores/Play/PVPlayCore/Core/Loader.cpp, Cores/Play/PVPlayCore/Core/PVPlayCore+Controls.mm, Cores/Play/PVPlayCore/Core/PVPlayCore+Video.mm, Cores/Play/PVPlayCore/Core/PVPlayCore.h, Cores/Play/PVPlayCore/Core/PVPlayCore.mm, Cores/Play/cmake/xcode_absolute_path_to_relative.py, PVSupport/Sources/PVSupport/EmulatorCore/PVEmulatorCore.h, PVSupport/Sources/PVSupport/EmulatorCore/PVEmulatorCore.m, Provenance.xcodeproj/project.pbxproj, Provenance/Emulator/PVGLViewController/PVGLViewController.m, Provenance/Emulator/PVGLViewController/PVMetalViewController.m
Updates Play Core to run on its own loop. This has:
- Adds skipEmulationLoop option on EmulatorCore, PVGL and PVMetal updated to not draw when emulation loop is turned off (prevents competing loops from writing to same frame buffer)
- Adds input handler to get input notice and handle the input without polling on the Play Controller
- Updates the rendering surfaces
- Adds script to copy lib molten as Core/Play/lib/libMoltenVK_Play to embed such that Play is able to maintain its own versioning of Molten as the support is expanded. 
Overall the emulation runs better with these changes, with less sound lags. It's been great playing this =] 
Merry Christmas and Happy Holidays, wishing everyone a holidays filled with happiness.
=> Play: Renderer Updates

Cores/PPSSPP/BuildFlags.xcconfig, Cores/PPSSPP/PVPPSSPP.xcodeproj/project.pbxproj, Cores/PPSSPP/PVPPSSPPCore/Core/MemArenaDarwin.cpp, Cores/PPSSPP/PVPPSSPPCore/Core/PPSSPPOGLViewController.swift, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore+Saves.mm, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore+Video.mm, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore.h, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore.mm, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore.swift, Cores/PPSSPP/cmake/PPSSPP.xcodeproj/project.pbxproj, Cores/PPSSPP/cmake/README.md, Cores/PPSSPP/cmake/generate.sh, Cores/PPSSPP/cmake/generate_post.sh, Cores/PPSSPP/cmake/xcode_absolute_path_to_relative.py
This has:
- Header / Absolute Path path adjustment script under cmake (updated generate.sh along with python script, created 2nd script generate_post.sh. To use this: 
1. Run generate.sh 
2. Open PPSSPP.xcodeproj / make appropriate customizations / compile / everything should compile ..etc
3. Run generate_post.sh (as Xcode will populate various absolute paths during the 1st run)
- There were a whole bunch of times where Memory weren't being allocated during startup. To fix this, new MemoryArena.cpp is added to PVPPSSPPCore/Core/ that is modified version of MemoryArenaDarwin.cpp in ppsspp, but is modified to loop vm_allocate  until proper memory address is found, then return the address
- PPSSPP Project file is modified with this change. So this now adds 1 more step to customizations …
=> PPSSPP: Feature Implementation - Cmake Script, MemInit, Screen Resizing ..etc.

Cores/Dolphin/PVDolphinCore/Core/PVDolphinCore+Controls.mm, Cores/Dolphin/PVDolphinCore/Core/PVDolphinCore.h, Cores/Dolphin/PVDolphinCore/Core/PVDolphinCore.mm, Cores/Dolphin/PVDolphinCore/Core/PVDolphinCore.swift, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore+Video.mm
Dolphin requires Wii system directory files to launch some games, so dolphin core now copies over entire Data/Sys to DolphinData directory (shared by all dolphin core games) if it doesn't exist. The games run much faster with cheat code disabled, so this is added as an option. (by default cheat code is disabled) Also nunchuck axis are added to dpad input so on screen dpad sends input for both types of games. Minor scaling adjustment on PPSSPP so stretch mode fills the screen. Nunchuck extension's added to the controller ini file so that games that require nunchuck to be connected to the wiimote recognizes it as connected. Dolphin's speed is very sensitive to initialization / cleanup between launches so additional cleanup after / before launch is added to keep speed.
=> Dolphin/PPSSPP: Additional Settings

Cores/Mednafen/MednafenGameCore.h, Cores/Mednafen/MednafenGameCore.mm, Cores/PPSSPP/PVPPSSPP/Core.plist, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore+Controls.mm, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore+Saves.mm, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore+Video.mm, Cores/PPSSPP/PVPPSSPPCore/Core/PVPPSSPPCore.mm, Cores/PPSSPP/PVPPSSPPCore/Core/VulkanGraphicsContext.h, PVLibrary/PVLibrary/Resources/systems.plist, Provenance/Controller/PVControllerViewController.swift, Provenance/Controller/Systems/PVPSPControllerViewController.swift, Provenance/Controller/Systems/PVPSXControllerViewController.swift, Provenance/Emulator/PVEmulatorVC/PVEmulatorViewController+Saves.swift
Modifies PPSSPP save such that lags / freezes caused by waiting for save to return during the game won't happen. The saves will take place in the background, with synchronous saving happening only when the game is paused.
Adds joypad support to PPSSPP to support games that require both. 
Adds generic internal flag to layout views to support Playstation / PPSSPP and other cores that might use joypad. Adjusted load to load save regardless of core version (version dialogue doesn't show on the ppsspp core, so the change will make the save load regardless)
Adds some adjustments to Mednafen to make on screen input work
=> PPSSPP: Fix Game Freezing after 5 minutes, Save Adjustments / Joypad support

Cores/DuckStation/cmake/CMakeFiles/3.25.1/CompilerIdC/CompilerIdC.xcodeproj/project.pbxproj, Cores/DuckStation/cmake/CMakeFiles/3.25.1/CompilerIdCXX/CompilerIdCXX.xcodeproj/project.pbxproj, Cores/DuckStation/cmake/dep/cpuinfo/cpuinfo.xcodeproj/project.pbxproj, Cores/DuckStation/cmake/dep/cpuinfo/deps/clog/clog.xcodeproj/project.pbxproj, Cores/DuckStation/cmake/dep/fmt/FMT.xcodeproj/project.pbxproj, Cores/DuckStation/cmake/dep/gsl/GSL.xcodeproj/project.pbxproj, Cores/DuckStation/cmake/duckstation.xcodeproj/project.pbxproj, Cores/Mupen64Plus-NX/PVMupen64Plus-NX.xcodeproj/project.pbxproj, Cores/Mupen64Plus-NX/cmake/.gitignore, Cores/Mupen64Plus-NX/cmake/Makefile, Cores/Yabause/PVYabause.xcodeproj/project.pbxproj, Cores/fuse/PVFuse.xcodeproj/project.pbxproj, Cores/fuse/PVFuse.xcodeproj/xcshareddata/xcschemes/PVFuse.xcscheme, Cores/fuse/cmake/.gitignore, Cores/fuse/cmake/Makefile.libretro, Cores/snes9x/cmake/.gitignore
Build script adjustments (absolute to relative, make files ..etc) This is same as usual, one important change, relevant to fuse and possibly others, is removal of "-Wl,-all_load -all_load" from the build target action project, along with container project (causes symbol conflicts when retroarch loads module if we have this flag in the dylib, with how dylib.c loads the modules in retroarch...) Other changes are misc changes which are same as usual. 
So happy to have this as part of provenance. I'll look at options after this =]
=> RetroArch: Build Scripts

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController+CollectionView.swift, Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
The landscape orientation on iOS has horizontal space on either side, this results in the value from `viewWillTransition` being wider than the collection view.
Using the `collectionView.bounds.size.width` instead solves the problem, this value is the same as the value from `viewWillTransition` on iPadOS.
=> Fix save position after orientation change on iOS

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift
Changing game library display or sort options now deselects the row after selection so the checkmark can be seen.
=> Prevent table row selection persisting

Provenance/PVAppDelegate.swift
Fixes setting the theme when set to auto, previously `self.window` was not yet defined causing incorrect theming.
=> Fix auto theme

Provenance/Emulator/CoreOptionsViewController.swift, Provenance/Settings/Cells/SliderCell.swift, Provenance/Settings/Custom Rows/SliderRow.swift
Displays the detail text that is often available.
=> Fix slider cell detail text

Provenance.xcodeproj/project.pbxproj
Fixes the following crash with the automatically built tvOS builds:
```
Library not loaded: @rpath/PVLogging.framework/PVLogging
```
=> Fix tvOS build

Provenance/Game Library/UI/Game Library/CollectionViewController/PVGameLibraryViewController.swift, Provenance/Game Library/UI/PVConflictViewController.swift
Fixes the missing title on tvOS, removes superfluous empty cells on iOS, and fixes the status bar UI when the initial conflict alert is presented. tvOS empty cell selection has also been fixed along with removing conflicts.
=> Fix conflict UI issues

.github/workflows/build.yml
=> build.yml test deriveddata caching

PVSupport/Sources/PVSupport/CoreOptions/CoreOptions+Serialization.swift
Fixes warnings on string formatting.
Standardize classname to utf8 on read/write
=> CoreOptions+Serialization fix warnings on strings, utf8 equal

.github/workflows/build.yml, Provenance.xcodeproj/project.pbxproj, Provenance/JIT/DOLJitManager.m
Compile workflow - this has 2 parts:
* https://github.com/Provenance-Emu/O2EM-Core/pull/1
* With O2EM PR merged this should compile on all platforms
=> compile: build workflow

PVLibrary/PVLibrary/Resources/systems.plist
=> Fix N64 C button position

Cores/Mednafen/Sources/MednafenGameCoreOptions/MednafenGameCoreOptions.swift, PVUI/Sources/PVUIBase/GameLaunching/GameLaunchingViewController.swift, Provenance/PVAppDelegate.swift
1.  Fix Mednafen PSX - currently it's required to set cd.image_memcache to true so this sets the default value of the core option to true (could also just remove for now)
2.  Fixes Save state loading for mednafen by forcing relevant functions accessing Realm to MainActor
3.  Forgot to add some important sequencing on App Delegate that ensures proper set up of directories and caches on first load
___
enhancement, bug_fix
___
- Changed the default value of the `cd.image_memcache_option` to `true` in the Mednafen core options to improve emulation performance.
- Fixed save state loading issues by ensuring relevant functions are executed on the `MainActor`.
- Enhanced the app delegate setup by initializing systems and reloading the cache in a single task, removing redundant database refresh …
=> Mednafen PSX & Save States Crashing + Game Importer Setup

Provenance/Main UI/PVAppDelegate.swift
This PR hooks up the original implementations (with slight tweak) of the 3 settings reset options.  
This PR hooks up the original implementations (with slight tweak) of the 3 settings reset options.  
I did once encounter a crash that I could not repro in this PR - please test all options to see If anything is crashing.
test reset works without error
=> Bugfix - fixes reset settings menu items that weren't hooked up in SwiftUI

Cores/Desmume2015/PVDesmume2015.xcodeproj/project.pbxproj, Cores/FCEU/PVFCEU.xcodeproj/project.pbxproj, Cores/GameMusicEmu/PVGME.xcodeproj/project.pbxproj, Cores/Genesis-Plus-GX/PVGenesis.xcodeproj/project.pbxproj, Cores/Mupen64Plus/PVMupen64Plus.xcodeproj/project.pbxproj, Cores/PPSSPP/PVPPSSPP.xcodeproj/project.pbxproj, Cores/Potator/PVPotator.xcodeproj/project.pbxproj, Cores/ProSystem/Package.swift, Cores/VecX/PVVecX.xcodeproj/project.pbxproj, Cores/VisualBoyAdvance-M/Package.swift, Cores/snes9x/PVSNES9x.xcodeproj/project.pbxproj, PVAudio/Package.swift, PVCoreAudio/Package.swift, PVCoreBridge/Package.swift, PVCoreLoader/Package.swift, PVCoreObjCBridge/Package.swift, PVEmulatorCore/Package.swift, PVHashing/Package.swift, PVLibrary/Sources/PVLibrary/Importer/Services/GameImporter/GameImporter.swift, PVObjCUtils/Package.swift, PVPlists/Package.swift, PVPrimitives/Package.swift, PVSettings/Package.swift, PVSupport/Package.swift
Removes the need to copy imports to a conflicts folder when conflicts are detected.  (also updates libraries and projects to iOS 16).
=> Enhancement - Importer stability when conflicts detected

Cores/emuThree/PVEmuThreeCore/Core/PVEmuThreeCoreOptions.swift
I noticed that most options that have 'requiresRestart: true' do not actually apply on restart. These changes should (in theory) fix resolution upscaling not updating, cpu clock not updating, as well as some other core options. On Citra, most settings do not require a restart anyway, except for JIT.
I also added a description for Shader Accurate Mul.
This needs to be tested as I cannot build emuThree for myself. Resolution upscaling and cpu clock speed are the most important ones to check if they update while in game. Other options that I set requiresRestart to false are logging, new 3ds, async shader comp, and shader accurate mul.
___
Enhancement
___
- Changed `requiresRestart` to `false` for several core options.
- Updated descriptions for `CPU Clock Speed` and `Shader Accurate Mul`.
- …
=> Sets 'requiresRestart: false' instead of 'true' for some emuThree core options

PVLibrary/Sources/PVLibrary/Database/Realm Database/RomDatabase.swift
This enables sideloading of the iPad version on macOS.
It is possible to install the IPA using iOS App Signer with the `embedded.mobileprovision` provisioning profile. The issue is that app groups are not available with the free plan, so changing the `APP_GROUP_IDENTIFIER` doesn't work because `com.apple.security.application-groups` entitlements are not possible.
___
Bug fix
___
- Add file readability check for app group containers
- Improve app group support detection on iOS
- Fix sideloading compatibility for iPad apps on macOS
___
```mermaid
flowchart LR
A["App Group Check"] --> B["Container Exists?"]
B --> C["File Readable?"]
C --> D["Return Support Status"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant …
=> Check if app group container is readable
